// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bVumzfkpaXXcvNmP8r5aNd
// Component: BfO3nDBp8Oix

import * as React from "react";


import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName,
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions,
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bVumzfkpaXXcvNmP8r5aNd/projectcss
//import sty from "./PlasmicDashboard.module.css"; // plasmic-import: BfO3nDBp8Oix/css
import sty from "./PlasmicDashboard.module.css";
import QuestionMark1Icon from "./icons/PlasmicIcon__QuestionMark1"; // plasmic-import: yY_Xh4fGKtqL/icon
import Bell1Icon from "./icons/PlasmicIcon__Bell1"; // plasmic-import: n9zUMqSDbSlh/icon
import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: oIoWRcUyEgWn/icon
import Layout11Icon from "./icons/PlasmicIcon__Layout11"; // plasmic-import: zToZXXJTB9dc/icon
import FolderIcon from "./icons/PlasmicIcon__Folder"; // plasmic-import: 90X0AxWg__s9/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: hCmqTbEa_XEh/icon
import FarmerMarketIcon from "./icons/PlasmicIcon__FarmerMarket"; // plasmic-import: 5cySklPsBu5b/icon
import CalendarIcon from "./icons/PlasmicIcon__Calendar"; // plasmic-import: c4V_2BCP5vb8/icon
import FChatIcon from "./icons/PlasmicIcon__FChat"; // plasmic-import: 6b5_xU8yWQFY/icon
import CandlestickChartIcon from "./icons/PlasmicIcon__CandlestickChart"; // plasmic-import: ZYZreGho0u9b/icon
import WhiskersIcon from "./icons/PlasmicIcon__Whiskers"; // plasmic-import: 6QYFPKXZ9GqK/icon
import CurrencyDollar1Icon from "./icons/PlasmicIcon__CurrencyDollar1"; // plasmic-import: USBnaJoUy1KG/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: 6kUOcHOYzusH/icon
import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: 99I2RlQV67k2/icon
import ArrowUp1Icon from "./icons/PlasmicIcon__ArrowUp1"; // plasmic-import: LK1XmH1YC1N6/icon
import Calendar2Icon from "./icons/PlasmicIcon__Calendar2"; // plasmic-import: dFXdcIaHC61R/icon
import ChevronDownLargeIcon from "./icons/PlasmicIcon__ChevronDownLarge"; // plasmic-import: MF4N_3wKmh_O/icon
import ChevronLeftLargeIcon from "./icons/PlasmicIcon__ChevronLeftLarge"; // plasmic-import: d-ag9IpbSnw-/icon
import Menu5Icon from "./icons/PlasmicIcon__Menu5"; // plasmic-import: 7KzZjpFqGdS5/icon
import ChevronRightLargeIcon from "./icons/PlasmicIcon__ChevronRightLarge"; // plasmic-import: VaHzNZUH3H4M/icon
import FunnelIcon from "./icons/PlasmicIcon__Funnel"; // plasmic-import: LV7HMvfyS4Un/icon
import EditAltIcon from "./icons/PlasmicIcon__EditAlt"; // plasmic-import: dE6pqSHD6AWY/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: oBXrHBt942Or/icon
import Menu51Icon from "./icons/PlasmicIcon__Menu51"; // plasmic-import: QnHOpjV_SKMJ/icon
import EllipseIcon from "./icons/PlasmicIcon__Ellipse"; // plasmic-import: OL9uoJ4OqaKE/icon
import Line40Icon from "./icons/PlasmicIcon__Line40"; // plasmic-import: b_URD0RDolM4/icon
import chartRt8T6Nkpz3Qc from "./images/chart.svg"; // plasmic-import: RT8T6nkpz3Qc/picture
import DashboardSection from "./mdashboardsection";
import Dinaggregation, { PlasmicDinaggregation } from "./mdinaggregation";
import Thirdfinancialperformance from "../../Thirdfinancialperformance";
import PlasmicWorkflows from "./mbusinessprocess";
//import { useNavigation } from "./NavigationContext";
//import Thirdfinancialperformance from "../../Thirdfinancialperformance";
//import { useRouter } from "next/navigation"; 
createPlasmicElementProxy;

export type PlasmicDashboard__VariantMembers = {};
export type PlasmicDashboard__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboard__VariantsArgs;
export const PlasmicDashboard__VariantProps = new Array<VariantPropType>();

export type PlasmicDashboard__ArgsType = {};
type ArgPropType = keyof PlasmicDashboard__ArgsType;
export const PlasmicDashboard__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboard__OverridesType = {
  root?: Flex__<"div">;
  wireframe1?: Flex__<"div">;
  dashboardChartsAndTable1?: Flex__<"div">;
  container1?: Flex__<"div">;
  avatar1?: Flex__<"div">;
  rectangle?: Flex__<"div">;
  textbox1?: Flex__<"div">;
  container2?: Flex__<"div">;
  sidebarMenu1?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  sidebarMenu3?: Flex__<"div">;
  frame3?: Flex__<"div">;
  frame4?: Flex__<"div">;
  frame5?: Flex__<"div">;
  customerInsights?: Flex__<"div">;
  frame6?: Flex__<"div">;
  frame7?: Flex__<"div">;
  image?: Flex__<"div">;
  tag1?: Flex__<"div">;
  frame8?: Flex__<"div">;
  todayOct202022?: Flex__<"div">;
  container3?: Flex__<"div">;
  sales?: Flex__<"div">;
  container4?: Flex__<"div">;
  tag2?: Flex__<"div">;
  frame9?: Flex__<"div">;
  lineChart1?: Flex__<"div">;
  frame10?: Flex__<"div">;
  container5?: Flex__<"div">;
  tag3?: Flex__<"div">;
  frame11?: Flex__<"div">;
  dropdownButton1?: Flex__<"div">;
  container11?: Flex__<"div">;
  orders?: Flex__<"div">;
  button1?: Flex__<"div">;
  button2?: Flex__<"div">;
  text?: Flex__<"div">;
  button3?: Flex__<"div">;
  button4?: Flex__<"div">;
  button5?: Flex__<"div">;
  button6?: Flex__<"div">;
  button7?: Flex__<"div">;
  text2?: Flex__<"div">;
  button8?: Flex__<"div">;
  button9?: Flex__<"div">;
  button10?: Flex__<"div">;
  text3?: Flex__<"div">;
  button11?: Flex__<"div">;
  dropdownButton2?: Flex__<"div">;
  table1?: Flex__<"div">;
  row?: Flex__<"div">;
  frame12?: Flex__<"div">;
  frame13?: Flex__<"div">;
  frame14?: Flex__<"div">;
  _250000?: Flex__<"div">;
  frame15?: Flex__<"div">;
  _59?: Flex__<"div">;
  frame16?: Flex__<"div">;
  _5000?: Flex__<"div">;
  row2?: Flex__<"div">;
  frame17?: Flex__<"div">;
  _2500002?: Flex__<"div">;
  frame18?: Flex__<"div">;
  frame19?: Flex__<"div">;
  _20?: Flex__<"div">;
  frame20?: Flex__<"div">;
  _10000?: Flex__<"div">;
  frame21?: Flex__<"div">;
  row3?: Flex__<"div">;
  frame22?: Flex__<"div">;
  _19?: Flex__<"div">;
  frame23?: Flex__<"div">;
  frame24?: Flex__<"div">;
  _2500003?: Flex__<"div">;
  frame25?: Flex__<"div">;
  _8000?: Flex__<"div">;
  frame26?: Flex__<"div">;
  row4?: Flex__<"div">;
  frame27?: Flex__<"div">;
  frame28?: Flex__<"div">;
  frame29?: Flex__<"div">;
  image2?: Flex__<"div">;
  frame30?: Flex__<"div">;
  frame31?: Flex__<"div">;
  row5?: Flex__<"div">;
  frame32?: Flex__<"div">;
  frame33?: Flex__<"div">;
  image3?: Flex__<"div">;
  frame34?: Flex__<"div">;
  frame35?: Flex__<"div">;
  frame36?: Flex__<"div">;
  header?: Flex__<"div">;
  frame37?: Flex__<"div">;
  UnitsSold?: Flex__<"div">;
  frame38?: Flex__<"div">;
  GrowthRate?: Flex__<"div">;
  frame39?: Flex__<"div">;
  frame40?: Flex__<"div">;
  Revenue?: Flex__<"div">;
  frame41?: Flex__<"div">;
  Product?: Flex__<"div">;
  productB?: Flex__<"div">;
  product1?: Flex__<"div">;
  productA?: Flex__<"div">;
  container22?: Flex__<"div">;
  financialSummary?: Flex__<"div">;
  columnBarChart2?: Flex__<"div">;
  chart?: Flex__<"div">;
  rectangle2?: Flex__<"div">;
  rectangle3?: Flex__<"div">;
  rectangle4?: Flex__<"div">;
  rectangle5?: Flex__<"div">;
  rectangle6?: Flex__<"div">;
  rectangle7?: Flex__<"div">;
  rectangle8?: Flex__<"div">;
  rectangle9?: Flex__<"div">;
  rectangle10?: Flex__<"div">;
  rectangle11?: Flex__<"div">;
  rectangle12?: Flex__<"div">;
  rectangle13?: Flex__<"div">;
  rectangle14?: Flex__<"div">;
  rectangle15?: Flex__<"div">;
  rectangle16?: Flex__<"div">;
  _100?: Flex__<"div">;
  _200?: Flex__<"div">;
  _300?: Flex__<"div">;
  _400?: Flex__<"div">;
  _500?: Flex__<"div">;
  container26?: Flex__<"div">;
  customerSatisfaction?: Flex__<"div">;
  pieChart2?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  frame42?: Flex__<"div">;
  group?: Flex__<"div">;
  segmentA?: Flex__<"div">;
  group2?: Flex__<"div">;
  segmentB?: Flex__<"div">;
  group3?: Flex__<"div">;
  segmentC?: Flex__<"div">;
  frame43?: Flex__<"div">;
  riskIdentification?: Flex__<"div">;
};

export interface DefaultDashboardProps {
  className?: string;
}

const $$ = {};

function PlasmicDashboard__RenderFunc(props: {
  variants: PlasmicDashboard__VariantsArgs;
  args: PlasmicDashboard__ArgsType;
  overrides: PlasmicDashboard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const [activeSection, setActiveSection] = React.useState<string>("Dashboard"); 
  //const router = useRouter();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"wireframe1"}
            data-plasmic-override={overrides.wireframe1}
            className={classNames(projectcss.all, sty.wireframe1)}
          >
            <div
              data-plasmic-name={"dashboardChartsAndTable1"}
              data-plasmic-override={overrides.dashboardChartsAndTable1}
              className={classNames(
                projectcss.all,
                sty.dashboardChartsAndTable1
              )}
            >
              <div
                data-plasmic-name={"container1"}
                data-plasmic-override={overrides.container1}
                className={classNames(projectcss.all, sty.container1)}
              >
                <QuestionMark1Icon
                  className={classNames(projectcss.all, sty.svg__m6Bdn)}
                  role={"img"}
                />

                <Bell1Icon
                  className={classNames(projectcss.all, sty.svg__qc9Jx)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"avatar1"}
                  data-plasmic-override={overrides.avatar1}
                  className={classNames(projectcss.all, sty.avatar1)}
                >
                  <div
                    data-plasmic-name={"rectangle"}
                    data-plasmic-override={overrides.rectangle}
                    className={classNames(projectcss.all, sty.rectangle)}
                  />
                </div>
                <div
                  data-plasmic-name={"textbox1"}
                  data-plasmic-override={overrides.textbox1}
                  className={classNames(projectcss.all, sty.textbox1)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s9T8Z
                    )}
                  >
                    {"Search..."}
                  </div>
                  <SearchIcon
                    className={classNames(projectcss.all, sty.svg__htox4)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"container2"}
                data-plasmic-override={overrides.container2}
                className={classNames(projectcss.all, sty.container2)}
              >
                
                <div
                  data-plasmic-name={"sidebarMenu1"}
                  data-plasmic-override={overrides.sidebarMenu1}
                  className={classNames(projectcss.all, sty.sidebarMenu1)}
                >
                    <hr style={{ margin: "8px"}} />
                 
                    
                  <div
                  onClick={() => setActiveSection("Dashboard")}
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    className={classNames(projectcss.all, sty.frame)}
                  >
          
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bQeSb
                      )}
                    >
                      {"Dashboard"}
                    </div>
                    <Layout11Icon
                      className={classNames(projectcss.all, sty.svg__xiXAq)}
                      role={"img"}
                    />
                  </div>
                
                  <div
                  onClick={() => setActiveSection("Dinaggregation")}
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    className={classNames(projectcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oVpdM
                      )}
                    >
                      {"Data Integration & Aggregation"}
                    </div>
                    <FolderIcon
                      className={classNames(projectcss.all, sty.svg__sb9KL)}
                      role={"img"}
                    />
                  </div>
                </div>
                

                <div
                  data-plasmic-name={"sidebarMenu3"}
                  data-plasmic-override={overrides.sidebarMenu3}
                  className={classNames(projectcss.all, sty.sidebarMenu3)}
                >
                  <div
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zLenz
                      )}
                    >
                      {"Market and Competitive"}
                    </div>
                    <FarmerMarketIcon
                      className={classNames(projectcss.all, sty.svg__sgUvz)}
                      role={"img"}
                    />
                  </div>
                  <div
                  onClick={() => setActiveSection("BusinessProcess")}
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dEvr5
                      )}
                    >
                      {"Business Process Analysis:"}
                    </div>
                    <CalendarIcon
                      className={classNames(projectcss.all, sty.svg__kpkEn)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <div
                      data-plasmic-name={"customerInsights"}
                      data-plasmic-override={overrides.customerInsights}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.customerInsights
                      )}
                    >
                      {"Customer Insights "}
                    </div>
                    <FChatIcon
                      className={classNames(projectcss.all, sty.svg__jcOz9)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame6"}
                    data-plasmic-override={overrides.frame6}
                    className={classNames(projectcss.all, sty.frame6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Fgn0
                      )}
                    >
                      {"Financial Performance"}
                    </div>
                    <CandlestickChartIcon
                      className={classNames(projectcss.all, sty.svg__hmSsm)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame7"}
                    data-plasmic-override={overrides.frame7}
                    className={classNames(projectcss.all, sty.frame7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__r9EbL
                      )}
                    >
                      {"Risk Identification"}
                    </div>
                    <WhiskersIcon
                      className={classNames(projectcss.all, sty.svg__bDe5I)}
                      role={"img"}
                    />
                  </div>
                  
                </div>
                <div
                data-plasmic-name={"frame43"}
                data-plasmic-override={overrides.frame43}
                className={classNames(projectcss.all, sty.frame43)}
              >
                <div
                  data-plasmic-name={"riskIdentification"}
                  data-plasmic-override={overrides.riskIdentification}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.riskIdentification
                  )}
                >
                  {"Strategic Planning"}
                </div>
                <SearchIcon
                  className={classNames(projectcss.all, sty.svg___9Ngv4)}
                  role={"img"}
                />
              </div>
                <div
                
                  data-plasmic-name={"image"}
                  data-plasmic-override={overrides.image}
                  className={classNames(projectcss.all, sty.image)}
                /> 
              </div>
              
              
              {/* dynamic section - Display differenct sections on sidebar click */}
              <div className={classNames(projectcss.all, sty.dynamicSection)}>
                {activeSection === "Dashboard" && <DashboardSection />}
                {activeSection === "Dinaggregation" && <PlasmicDinaggregation />}
                {activeSection === "BusinessProcess" && <PlasmicWorkflows />}
              </div>

            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "wireframe1",
    "dashboardChartsAndTable1",
    "container1",
    "avatar1",
    "rectangle",
    "textbox1",
    "container2",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "tag1",
    "frame8",
    "todayOct202022",
    "container3",
    "sales",
    "container4",
    "tag2",
    "frame9",
    "lineChart1",
    "frame10",
    "container5",
    "tag3",
    "frame11",
    "dropdownButton1",
    "container11",
    "orders",
    "button1",
    "button2",
    "text",
    "button3",
    "button4",
    "button5",
    "button6",
    "button7",
    "text2",
    "button8",
    "button9",
    "button10",
    "text3",
    "button11",
    "dropdownButton2",
    "table1",
    "row",
    "frame12",
    "frame13",
    "frame14",
    "_250000",
    "frame15",
    "_59",
    "frame16",
    "_5000",
    "row2",
    "frame17",
    "_2500002",
    "frame18",
    "frame19",
    "_20",
    "frame20",
    "_10000",
    "frame21",
    "row3",
    "frame22",
    "_19",
    "frame23",
    "frame24",
    "_2500003",
    "frame25",
    "_8000",
    "frame26",
    "row4",
    "frame27",
    "frame28",
    "frame29",
    "image2",
    "frame30",
    "frame31",
    "row5",
    "frame32",
    "frame33",
    "image3",
    "frame34",
    "frame35",
    "frame36",
    "header",
    "frame37",
    "UnitsSold",
    "frame38",
    "GrowthRate",
    "frame39",
    "frame40",
    "Revenue",
    "frame41",
    "Product",
    "productB",
    "product1",
    "productA",
    "container22",
    "financialSummary",
    "columnBarChart2",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
    "_100",
    "_200",
    "_300",
    "_400",
    "_500",
    "container26",
    "customerSatisfaction",
    "pieChart2",
    "img",
    "frame42",
    "group",
    "segmentA",
    "group2",
    "segmentB",
    "group3",
    "segmentC",
    "frame43",
    "riskIdentification",
  ],
  wireframe1: [
    "wireframe1",
    "dashboardChartsAndTable1",
    "container1",
    "avatar1",
    "rectangle",
    "textbox1",
    "container2",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "tag1",
    "frame8",
    "todayOct202022",
    "container3",
    "sales",
    "container4",
    "tag2",
    "frame9",
    "lineChart1",
    "frame10",
    "container5",
    "tag3",
    "frame11",
    "dropdownButton1",
    "container11",
    "orders",
    "button1",
    "button2",
    "text",
    "button3",
    "button4",
    "button5",
    "button6",
    "button7",
    "text2",
    "button8",
    "button9",
    "button10",
    "text3",
    "button11",
    "dropdownButton2",
    "table1",
    "row",
    "frame12",
    "frame13",
    "frame14",
    "_250000",
    "frame15",
    "_59",
    "frame16",
    "_5000",
    "row2",
    "frame17",
    "_2500002",
    "frame18",
    "frame19",
    "_20",
    "frame20",
    "_10000",
    "frame21",
    "row3",
    "frame22",
    "_19",
    "frame23",
    "frame24",
    "_2500003",
    "frame25",
    "_8000",
    "frame26",
    "row4",
    "frame27",
    "frame28",
    "frame29",
    "image2",
    "frame30",
    "frame31",
    "row5",
    "frame32",
    "frame33",
    "image3",
    "frame34",
    "frame35",
    "frame36",
    "header",
    "frame37",
    "UnitsSold",
    "frame38",
    "GrowthRate",
    "frame39",
    "frame40",
    "Revenue",
    "frame41",
    "Product",
    "productB",
    "product1",
    "productA",
    "container22",
    "financialSummary",
    "columnBarChart2",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
    "_100",
    "_200",
    "_300",
    "_400",
    "_500",
    "container26",
    "customerSatisfaction",
    "pieChart2",
    "img",
    "frame42",
    "group",
    "segmentA",
    "group2",
    "segmentB",
    "group3",
    "segmentC",
    "frame43",
    "riskIdentification",
  ],
  dashboardChartsAndTable1: [
    "dashboardChartsAndTable1",
    "container1",
    "avatar1",
    "rectangle",
    "textbox1",
    "container2",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "tag1",
    "frame8",
    "todayOct202022",
    "container3",
    "sales",
    "container4",
    "tag2",
    "frame9",
    "lineChart1",
    "frame10",
    "container5",
    "tag3",
    "frame11",
    "dropdownButton1",
    "container11",
    "orders",
    "button1",
    "button2",
    "text",
    "button3",
    "button4",
    "button5",
    "button6",
    "button7",
    "text2",
    "button8",
    "button9",
    "button10",
    "text3",
    "button11",
    "dropdownButton2",
    "table1",
    "row",
    "frame12",
    "frame13",
    "frame14",
    "_250000",
    "frame15",
    "_59",
    "frame16",
    "_5000",
    "row2",
    "frame17",
    "_2500002",
    "frame18",
    "frame19",
    "_20",
    "frame20",
    "_10000",
    "frame21",
    "row3",
    "frame22",
    "_19",
    "frame23",
    "frame24",
    "_2500003",
    "frame25",
    "_8000",
    "frame26",
    "row4",
    "frame27",
    "frame28",
    "frame29",
    "image2",
    "frame30",
    "frame31",
    "row5",
    "frame32",
    "frame33",
    "image3",
    "frame34",
    "frame35",
    "frame36",
    "header",
    "frame37",
    "UnitsSold",
    "frame38",
    "GrowthRate",
    "frame39",
    "frame40",
    "Revenue",
    "frame41",
    "Product",
    "productB",
    "product1",
    "productA",
    "container22",
    "financialSummary",
    "columnBarChart2",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
    "_100",
    "_200",
    "_300",
    "_400",
    "_500",
    "container26",
    "customerSatisfaction",
    "pieChart2",
    "img",
    "frame42",
    "group",
    "segmentA",
    "group2",
    "segmentB",
    "group3",
    "segmentC",
    "frame43",
    "riskIdentification",
  ],
  container1: ["container1", "avatar1", "rectangle", "textbox1"],
  avatar1: ["avatar1", "rectangle"],
  rectangle: ["rectangle"],
  textbox1: ["textbox1"],
  container2: [
    "container2",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
  ],
  sidebarMenu1: ["sidebarMenu1", "frame", "frame2"],
  frame: ["frame"],
  frame2: ["frame2"],
  sidebarMenu3: [
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
  ],
  frame3: ["frame3"],
  frame4: ["frame4"],
  frame5: ["frame5", "customerInsights"],
  customerInsights: ["customerInsights"],
  frame6: ["frame6"],
  frame7: ["frame7"],
  image: ["image"],
  tag1: ["tag1", "frame8", "todayOct202022"],
  frame8: ["frame8", "todayOct202022"],
  todayOct202022: ["todayOct202022"],
  container3: [
    "container3",
    "sales",
    "container4",
    "tag2",
    "frame9",
    "lineChart1",
    "frame10",
    "container5",
    "tag3",
    "frame11",
  ],
  sales: ["sales"],
  container4: ["container4", "tag2", "frame9"],
  tag2: ["tag2", "frame9"],
  frame9: ["frame9"],
  lineChart1: ["lineChart1", "frame10"],
  frame10: ["frame10"],
  container5: ["container5", "tag3", "frame11"],
  tag3: ["tag3", "frame11"],
  frame11: ["frame11"],
  dropdownButton1: ["dropdownButton1"],
  container11: [
    "container11",
    "orders",
    "button1",
    "button2",
    "text",
    "button3",
    "button4",
    "button5",
    "button6",
    "button7",
    "text2",
    "button8",
    "button9",
    "button10",
    "text3",
    "button11",
    "dropdownButton2",
    "table1",
    "row",
    "frame12",
    "frame13",
    "frame14",
    "_250000",
    "frame15",
    "_59",
    "frame16",
    "_5000",
    "row2",
    "frame17",
    "_2500002",
    "frame18",
    "frame19",
    "_20",
    "frame20",
    "_10000",
    "frame21",
    "row3",
    "frame22",
    "_19",
    "frame23",
    "frame24",
    "_2500003",
    "frame25",
    "_8000",
    "frame26",
    "row4",
    "frame27",
    "frame28",
    "frame29",
    "image2",
    "frame30",
    "frame31",
    "row5",
    "frame32",
    "frame33",
    "image3",
    "frame34",
    "frame35",
    "frame36",
    "header",
    "frame37",
    "UnitsSold",
    "frame38",
    "GrowthRate",
    "frame39",
    "frame40",
    "Revenue",
    "frame41",
    "Product",
    "productB",
    "product1",
    "productA",
  ],
  orders: ["orders"],
  button1: ["button1"],
  button2: ["button2", "text"],
  text: ["text"],
  button3: ["button3"],
  button4: ["button4"],
  button5: ["button5"],
  button6: ["button6"],
  button7: ["button7", "text2"],
  text2: ["text2"],
  button8: ["button8"],
  button9: ["button9"],
  button10: ["button10", "text3"],
  text3: ["text3"],
  button11: ["button11"],
  dropdownButton2: ["dropdownButton2"],
  table1: [
    "table1",
    "row",
    "frame12",
    "frame13",
    "frame14",
    "_250000",
    "frame15",
    "_59",
    "frame16",
    "_5000",
    "row2",
    "frame17",
    "_2500002",
    "frame18",
    "frame19",
    "_20",
    "frame20",
    "_10000",
    "frame21",
    "row3",
    "frame22",
    "_19",
    "frame23",
    "frame24",
    "_2500003",
    "frame25",
    "_8000",
    "frame26",
    "row4",
    "frame27",
    "frame28",
    "frame29",
    "image2",
    "frame30",
    "frame31",
    "row5",
    "frame32",
    "frame33",
    "image3",
    "frame34",
    "frame35",
    "frame36",
    "header",
    "frame37",
    "UnitsSold",
    "frame38",
    "GrowthRate",
    "frame39",
    "frame40",
    "Revenue",
    "frame41",
    "Product",
    "productB",
    "product1",
    "productA",
  ],
  row: [
    "row",
    "frame12",
    "frame13",
    "frame14",
    "_250000",
    "frame15",
    "_59",
    "frame16",
    "_5000",
  ],
  frame12: ["frame12"],
  frame13: ["frame13"],
  frame14: ["frame14", "_250000"],
  _250000: ["_250000"],
  frame15: ["frame15", "_59"],
  _59: ["_59"],
  frame16: ["frame16", "_5000"],
  _5000: ["_5000"],
  row2: [
    "row2",
    "frame17",
    "_2500002",
    "frame18",
    "frame19",
    "_20",
    "frame20",
    "_10000",
    "frame21",
  ],
  frame17: ["frame17", "_2500002"],
  _2500002: ["_2500002"],
  frame18: ["frame18"],
  frame19: ["frame19", "_20"],
  _20: ["_20"],
  frame20: ["frame20", "_10000"],
  _10000: ["_10000"],
  frame21: ["frame21"],
  row3: [
    "row3",
    "frame22",
    "_19",
    "frame23",
    "frame24",
    "_2500003",
    "frame25",
    "_8000",
    "frame26",
  ],
  frame22: ["frame22", "_19"],
  _19: ["_19"],
  frame23: ["frame23"],
  frame24: ["frame24", "_2500003"],
  _2500003: ["_2500003"],
  frame25: ["frame25", "_8000"],
  _8000: ["_8000"],
  frame26: ["frame26"],
  row4: [
    "row4",
    "frame27",
    "frame28",
    "frame29",
    "image2",
    "frame30",
    "frame31",
  ],
  frame27: ["frame27"],
  frame28: ["frame28"],
  frame29: ["frame29", "image2"],
  image2: ["image2"],
  frame30: ["frame30"],
  frame31: ["frame31"],
  row5: [
    "row5",
    "frame32",
    "frame33",
    "image3",
    "frame34",
    "frame35",
    "frame36",
  ],
  frame32: ["frame32"],
  frame33: ["frame33", "image3"],
  image3: ["image3"],
  frame34: ["frame34"],
  frame35: ["frame35"],
  frame36: ["frame36"],
  header: [
    "header",
    "frame37",
    "UnitsSold",
    "frame38",
    "GrowthRate",
    "frame39",
    "frame40",
    "Revenue",
    "frame41",
    "Product",
  ],
  frame37: ["frame37", "UnitsSold"],
  UnitsSold: ["UnitsSold"],
  frame38: ["frame38", "GrowthRate"],
  GrowthRate: ["GrowthRate"],
  frame39: ["frame39"],
  frame40: ["frame40", "Revenue"],
  Revenue: ["Revenue"],
  frame41: ["frame41", "Product"],
  Product: ["Product"],
  productB: ["productB"],
  product1: ["product1"],
  productA: ["productA"],
  container22: [
    "container22",
    "financialSummary",
    "columnBarChart2",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
    "_100",
    "_200",
    "_300",
    "_400",
    "_500",
  ],
  financialSummary: ["financialSummary"],
  columnBarChart2: [
    "columnBarChart2",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
  ],
  chart: [
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
  ],
  rectangle2: ["rectangle2"],
  rectangle3: ["rectangle3"],
  rectangle4: ["rectangle4"],
  rectangle5: ["rectangle5"],
  rectangle6: ["rectangle6"],
  rectangle7: ["rectangle7"],
  rectangle8: ["rectangle8"],
  rectangle9: ["rectangle9"],
  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  rectangle12: ["rectangle12"],
  rectangle13: ["rectangle13"],
  rectangle14: ["rectangle14"],
  rectangle15: ["rectangle15"],
  rectangle16: ["rectangle16"],
  _100: ["_100"],
  _200: ["_200"],
  _300: ["_300"],
  _400: ["_400"],
  _500: ["_500"],
  container26: [
    "container26",
    "customerSatisfaction",
    "pieChart2",
    "img",
    "frame42",
    "group",
    "segmentA",
    "group2",
    "segmentB",
    "group3",
    "segmentC",
  ],
  customerSatisfaction: ["customerSatisfaction"],
  pieChart2: [
    "pieChart2",
    "img",
    "frame42",
    "group",
    "segmentA",
    "group2",
    "segmentB",
    "group3",
    "segmentC",
  ],
  img: ["img"],
  frame42: [
    "frame42",
    "group",
    "segmentA",
    "group2",
    "segmentB",
    "group3",
    "segmentC",
  ],
  group: ["group", "segmentA"],
  segmentA: ["segmentA"],
  group2: ["group2", "segmentB"],
  segmentB: ["segmentB"],
  group3: ["group3", "segmentC"],
  segmentC: ["segmentC"],
  frame43: ["frame43", "riskIdentification"],
  riskIdentification: ["riskIdentification"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  wireframe1: "div";
  dashboardChartsAndTable1: "div";
  container1: "div";
  avatar1: "div";
  rectangle: "div";
  textbox1: "div";
  container2: "div";
  sidebarMenu1: "div";
  frame: "div";
  frame2: "div";
  sidebarMenu3: "div";
  frame3: "div";
  frame4: "div";
  frame5: "div";
  customerInsights: "div";
  frame6: "div";
  frame7: "div";
  image: "div";
  tag1: "div";
  frame8: "div";
  todayOct202022: "div";
  container3: "div";
  sales: "div";
  container4: "div";
  tag2: "div";
  frame9: "div";
  lineChart1: "div";
  frame10: "div";
  container5: "div";
  tag3: "div";
  frame11: "div";
  dropdownButton1: "div";
  container11: "div";
  orders: "div";
  button1: "div";
  button2: "div";
  text: "div";
  button3: "div";
  button4: "div";
  button5: "div";
  button6: "div";
  button7: "div";
  text2: "div";
  button8: "div";
  button9: "div";
  button10: "div";
  text3: "div";
  button11: "div";
  dropdownButton2: "div";
  table1: "div";
  row: "div";
  frame12: "div";
  frame13: "div";
  frame14: "div";
  _250000: "div";
  frame15: "div";
  _59: "div";
  frame16: "div";
  _5000: "div";
  row2: "div";
  frame17: "div";
  _2500002: "div";
  frame18: "div";
  frame19: "div";
  _20: "div";
  frame20: "div";
  _10000: "div";
  frame21: "div";
  row3: "div";
  frame22: "div";
  _19: "div";
  frame23: "div";
  frame24: "div";
  _2500003: "div";
  frame25: "div";
  _8000: "div";
  frame26: "div";
  row4: "div";
  frame27: "div";
  frame28: "div";
  frame29: "div";
  image2: "div";
  frame30: "div";
  frame31: "div";
  row5: "div";
  frame32: "div";
  frame33: "div";
  image3: "div";
  frame34: "div";
  frame35: "div";
  frame36: "div";
  header: "div";
  frame37: "div";
  UnitsSold: "div";
  frame38: "div";
  GrowthRate: "div";
  frame39: "div";
  frame40: "div";
  Revenue: "div";
  frame41: "div";
  Product: "div";
  productB: "div";
  product1: "div";
  productA: "div";
  container22: "div";
  financialSummary: "div";
  columnBarChart2: "div";
  chart: "div";
  rectangle2: "div";
  rectangle3: "div";
  rectangle4: "div";
  rectangle5: "div";
  rectangle6: "div";
  rectangle7: "div";
  rectangle8: "div";
  rectangle9: "div";
  rectangle10: "div";
  rectangle11: "div";
  rectangle12: "div";
  rectangle13: "div";
  rectangle14: "div";
  rectangle15: "div";
  rectangle16: "div";
  _100: "div";
  _200: "div";
  _300: "div";
  _400: "div";
  _500: "div";
  container26: "div";
  customerSatisfaction: "div";
  pieChart2: "div";
  img: typeof PlasmicImg__;
  frame42: "div";
  group: "div";
  segmentA: "div";
  group2: "div";
  segmentB: "div";
  group3: "div";
  segmentC: "div";
  frame43: "div";
  riskIdentification: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboard__VariantsArgs;
    args?: PlasmicDashboard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDashboard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDashboard__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDashboard__ArgProps,
          internalVariantPropNames: PlasmicDashboard__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDashboard";
  } else {
    func.displayName = `PlasmicDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicDashboard = Object.assign(
  // Top-level PlasmicDashboard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wireframe1: makeNodeComponent("wireframe1"),
    dashboardChartsAndTable1: makeNodeComponent("dashboardChartsAndTable1"),
    container1: makeNodeComponent("container1"),
    avatar1: makeNodeComponent("avatar1"),
    rectangle: makeNodeComponent("rectangle"),
    textbox1: makeNodeComponent("textbox1"),
    container2: makeNodeComponent("container2"),
    sidebarMenu1: makeNodeComponent("sidebarMenu1"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    sidebarMenu3: makeNodeComponent("sidebarMenu3"),
    frame3: makeNodeComponent("frame3"),
    frame4: makeNodeComponent("frame4"),
    frame5: makeNodeComponent("frame5"),
    customerInsights: makeNodeComponent("customerInsights"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    image: makeNodeComponent("image"),
    tag1: makeNodeComponent("tag1"),
    frame8: makeNodeComponent("frame8"),
    todayOct202022: makeNodeComponent("todayOct202022"),
    container3: makeNodeComponent("container3"),
    sales: makeNodeComponent("sales"),
    container4: makeNodeComponent("container4"),
    tag2: makeNodeComponent("tag2"),
    frame9: makeNodeComponent("frame9"),
    lineChart1: makeNodeComponent("lineChart1"),
    frame10: makeNodeComponent("frame10"),
    container5: makeNodeComponent("container5"),
    tag3: makeNodeComponent("tag3"),
    frame11: makeNodeComponent("frame11"),
    dropdownButton1: makeNodeComponent("dropdownButton1"),
    container11: makeNodeComponent("container11"),
    orders: makeNodeComponent("orders"),
    button1: makeNodeComponent("button1"),
    button2: makeNodeComponent("button2"),
    text: makeNodeComponent("text"),
    button3: makeNodeComponent("button3"),
    button4: makeNodeComponent("button4"),
    button5: makeNodeComponent("button5"),
    button6: makeNodeComponent("button6"),
    button7: makeNodeComponent("button7"),
    text2: makeNodeComponent("text2"),
    button8: makeNodeComponent("button8"),
    button9: makeNodeComponent("button9"),
    button10: makeNodeComponent("button10"),
    text3: makeNodeComponent("text3"),
    button11: makeNodeComponent("button11"),
    dropdownButton2: makeNodeComponent("dropdownButton2"),
    table1: makeNodeComponent("table1"),
    row: makeNodeComponent("row"),
    frame12: makeNodeComponent("frame12"),
    frame13: makeNodeComponent("frame13"),
    frame14: makeNodeComponent("frame14"),
    _250000: makeNodeComponent("_250000"),
    frame15: makeNodeComponent("frame15"),
    _59: makeNodeComponent("_59"),
    frame16: makeNodeComponent("frame16"),
    _5000: makeNodeComponent("_5000"),
    row2: makeNodeComponent("row2"),
    frame17: makeNodeComponent("frame17"),
    _2500002: makeNodeComponent("_2500002"),
    frame18: makeNodeComponent("frame18"),
    frame19: makeNodeComponent("frame19"),
    _20: makeNodeComponent("_20"),
    frame20: makeNodeComponent("frame20"),
    _10000: makeNodeComponent("_10000"),
    frame21: makeNodeComponent("frame21"),
    row3: makeNodeComponent("row3"),
    frame22: makeNodeComponent("frame22"),
    _19: makeNodeComponent("_19"),
    frame23: makeNodeComponent("frame23"),
    frame24: makeNodeComponent("frame24"),
    _2500003: makeNodeComponent("_2500003"),
    frame25: makeNodeComponent("frame25"),
    _8000: makeNodeComponent("_8000"),
    frame26: makeNodeComponent("frame26"),
    row4: makeNodeComponent("row4"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    frame29: makeNodeComponent("frame29"),
    image2: makeNodeComponent("image2"),
    frame30: makeNodeComponent("frame30"),
    frame31: makeNodeComponent("frame31"),
    row5: makeNodeComponent("row5"),
    frame32: makeNodeComponent("frame32"),
    frame33: makeNodeComponent("frame33"),
    image3: makeNodeComponent("image3"),
    frame34: makeNodeComponent("frame34"),
    frame35: makeNodeComponent("frame35"),
    frame36: makeNodeComponent("frame36"),
    header: makeNodeComponent("header"),
    frame37: makeNodeComponent("frame37"),
    UnitsSold: makeNodeComponent("UnitsSold"),
    frame38: makeNodeComponent("frame38"),
    GrowthRate: makeNodeComponent("GrowthRate"),
    frame39: makeNodeComponent("frame39"),
    frame40: makeNodeComponent("frame40"),
    Revenue: makeNodeComponent("Revenue"),
    frame41: makeNodeComponent("frame41"),
    Product: makeNodeComponent("Product"),
    productB: makeNodeComponent("productB"),
    product1: makeNodeComponent("product1"),
    productA: makeNodeComponent("productA"),
    container22: makeNodeComponent("container22"),
    financialSummary: makeNodeComponent("financialSummary"),
    columnBarChart2: makeNodeComponent("columnBarChart2"),
    chart: makeNodeComponent("chart"),
    rectangle2: makeNodeComponent("rectangle2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle4: makeNodeComponent("rectangle4"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle7: makeNodeComponent("rectangle7"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle13: makeNodeComponent("rectangle13"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle15: makeNodeComponent("rectangle15"),
    rectangle16: makeNodeComponent("rectangle16"),
    _100: makeNodeComponent("_100"),
    _200: makeNodeComponent("_200"),
    _300: makeNodeComponent("_300"),
    _400: makeNodeComponent("_400"),
    _500: makeNodeComponent("_500"),
    container26: makeNodeComponent("container26"),
    customerSatisfaction: makeNodeComponent("customerSatisfaction"),
    pieChart2: makeNodeComponent("pieChart2"),
    img: makeNodeComponent("img"),
    frame42: makeNodeComponent("frame42"),
    group: makeNodeComponent("group"),
    segmentA: makeNodeComponent("segmentA"),
    group2: makeNodeComponent("group2"),
    segmentB: makeNodeComponent("segmentB"),
    group3: makeNodeComponent("group3"),
    segmentC: makeNodeComponent("segmentC"),
    frame43: makeNodeComponent("frame43"),
    riskIdentification: makeNodeComponent("riskIdentification"),

    // Metadata about props expected for PlasmicDashboard
    internalVariantProps: PlasmicDashboard__VariantProps,
    internalArgProps: PlasmicDashboard__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: "",
    },
  }
);

export default PlasmicDashboard;
/* prettier-ignore-end */
