// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bVumzfkpaXXcvNmP8r5aNd
// Component: s_yP0CQ6Gbqb

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bVumzfkpaXXcvNmP8r5aNd/projectcss
import sty from "./PlasmicOurcommunity.module.css"; // plasmic-import: s_yP0CQ6Gbqb/css

import MailIcon from "./icons/PlasmicIcon__Mail"; // plasmic-import: eJzxYIWUJGCN/icon
import Group6Icon from "./icons/PlasmicIcon__Group6"; // plasmic-import: 0jR7aPTrU-WU/icon
import Group7Icon from "./icons/PlasmicIcon__Group7"; // plasmic-import: 0OBtqVU7rnGp/icon
import Group8Icon from "./icons/PlasmicIcon__Group8"; // plasmic-import: negmLw9Lahn0/icon
import Group9Icon from "./icons/PlasmicIcon__Group9"; // plasmic-import: n7dWUzZcXnah/icon
import Group10Icon from "./icons/PlasmicIcon__Group10"; // plasmic-import: zwNBCeTF11Yl/icon
import Group11Icon from "./icons/PlasmicIcon__Group11"; // plasmic-import: zdv3NGeyNFLF/icon
import Group12Icon from "./icons/PlasmicIcon__Group12"; // plasmic-import: yDlgbJ3RlFD9/icon
import Group13Icon from "./icons/PlasmicIcon__Group13"; // plasmic-import: LK_4Rog76YJR/icon
import Group14Icon from "./icons/PlasmicIcon__Group14"; // plasmic-import: 0NnTZcIzEmqS/icon
import Group15Icon from "./icons/PlasmicIcon__Group15"; // plasmic-import: pvytRA2nWTFy/icon
import Group16Icon from "./icons/PlasmicIcon__Group16"; // plasmic-import: -QphWdu4LOoB/icon
import Group17Icon from "./icons/PlasmicIcon__Group17"; // plasmic-import: SXeyP55Srhpg/icon
import Group18Icon from "./icons/PlasmicIcon__Group18"; // plasmic-import: mbAvXjogMfuE/icon
import Group19Icon from "./icons/PlasmicIcon__Group19"; // plasmic-import: bCB2QDFUTpjq/icon
import Group20Icon from "./icons/PlasmicIcon__Group20"; // plasmic-import: YvfMhLDmUC_j/icon
import Group21Icon from "./icons/PlasmicIcon__Group21"; // plasmic-import: wIk9TB_CYxzT/icon
import ArrowRightIcon from "./icons/PlasmicIcon__ArrowRight"; // plasmic-import: cHuLe7oK0FCN/icon

createPlasmicElementProxy;

export type PlasmicOurcommunity__VariantMembers = {};
export type PlasmicOurcommunity__VariantsArgs = {};
type VariantPropType = keyof PlasmicOurcommunity__VariantsArgs;
export const PlasmicOurcommunity__VariantProps = new Array<VariantPropType>();

export type PlasmicOurcommunity__ArgsType = {};
type ArgPropType = keyof PlasmicOurcommunity__ArgsType;
export const PlasmicOurcommunity__ArgProps = new Array<ArgPropType>();

export type PlasmicOurcommunity__OverridesType = {
  root?: Flex__<"div">;
  wireframe16?: Flex__<"div">;
  newsListing?: Flex__<"div">;
  container163?: Flex__<"div">;
  dropdownButton8?: Flex__<"div">;
  image61?: Flex__<"div">;
  group?: Flex__<"div">;
  group2?: Flex__<"div">;
  group3?: Flex__<"div">;
  group4?: Flex__<"div">;
  container164?: Flex__<"div">;
  image62?: Flex__<"div">;
  rectangle31?: Flex__<"div">;
  expandYourWorld?: Flex__<"div">;
  sereneEscapesPodcast?: Flex__<"div">;
  container179?: Flex__<"div">;
  image71?: Flex__<"div">;
  button140?: Flex__<"div">;
  container180?: Flex__<"div">;
  image72?: Flex__<"div">;
  image73?: Flex__<"div">;
  image74?: Flex__<"div">;
  image75?: Flex__<"div">;
  image76?: Flex__<"div">;
  image77?: Flex__<"div">;
};

export interface DefaultOurcommunityProps {
  className?: string;
}

const $$ = {};

function PlasmicOurcommunity__RenderFunc(props: {
  variants: PlasmicOurcommunity__VariantsArgs;
  args: PlasmicOurcommunity__ArgsType;
  overrides: PlasmicOurcommunity__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"wireframe16"}
            data-plasmic-override={overrides.wireframe16}
            className={classNames(projectcss.all, sty.wireframe16)}
          >
            <div
              data-plasmic-name={"newsListing"}
              data-plasmic-override={overrides.newsListing}
              className={classNames(projectcss.all, sty.newsListing)}
            >
              <div
                data-plasmic-name={"container163"}
                data-plasmic-override={overrides.container163}
                className={classNames(projectcss.all, sty.container163)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y5ZNk
                  )}
                >
                  {"Help center"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qeyh0
                  )}
                >
                  {
                    "Discover a premier digital consumer brand offering comprehensive travel information and inspiration. With a rich heritage of over 30 years in print and two decades online, this platform provides accurate content on top global destinations. From cities and airports to resorts and attractions, our dedicated editorial team updates the portal daily, attracting millions of unique users monthly."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__flQa9
                  )}
                >
                  {"DESTINATIONS"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ec0Zz
                  )}
                >
                  {"TRIPS"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ce03P
                  )}
                >
                  {"Vlogs"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___819E3
                  )}
                >
                  {"COMMUNITY"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__whwTh
                  )}
                >
                  {"SHOP"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c7Fjs
                  )}
                >
                  {"Events"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Mrig
                  )}
                >
                  {"Podcasts"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o9Z6L
                  )}
                >
                  {"ABOUT"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ds2B5
                  )}
                >
                  {"FAQs"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kyTqe
                  )}
                >
                  {"NEWS"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b4CIs
                  )}
                >
                  {"Subscribe to our channel"}
                </div>
                <div
                  data-plasmic-name={"dropdownButton8"}
                  data-plasmic-override={overrides.dropdownButton8}
                  className={classNames(projectcss.all, sty.dropdownButton8)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0Po4G
                    )}
                  >
                    {"Email"}
                  </div>
                  <MailIcon
                    className={classNames(projectcss.all, sty.svg__adxh5)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"image61"}
                  data-plasmic-override={overrides.image61}
                  className={classNames(projectcss.all, sty.image61)}
                >
                  <div
                    data-plasmic-name={"group"}
                    data-plasmic-override={overrides.group}
                    className={classNames(projectcss.all, sty.group)}
                  >
                    <div
                      data-plasmic-name={"group2"}
                      data-plasmic-override={overrides.group2}
                      className={classNames(projectcss.all, sty.group2)}
                    >
                      <div
                        data-plasmic-name={"group3"}
                        data-plasmic-override={overrides.group3}
                        className={classNames(projectcss.all, sty.group3)}
                      >
                        <div
                          data-plasmic-name={"group4"}
                          data-plasmic-override={overrides.group4}
                          className={classNames(projectcss.all, sty.group4)}
                        >
                          <Group6Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__eWuW5
                            )}
                            role={"img"}
                          />

                          <Group7Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__oYgz
                            )}
                            role={"img"}
                          />

                          <Group8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___0NRkG
                            )}
                            role={"img"}
                          />

                          <Group9Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__asMpG
                            )}
                            role={"img"}
                          />

                          <Group10Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___7RZft
                            )}
                            role={"img"}
                          />

                          <Group11Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uRj1P
                            )}
                            role={"img"}
                          />

                          <Group12Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kSfZl
                            )}
                            role={"img"}
                          />

                          <Group13Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nhAah
                            )}
                            role={"img"}
                          />

                          <Group14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tJ2Y7
                            )}
                            role={"img"}
                          />

                          <Group15Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bzqXb
                            )}
                            role={"img"}
                          />

                          <Group16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__z1LE
                            )}
                            role={"img"}
                          />

                          <Group17Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__j7O0P
                            )}
                            role={"img"}
                          />

                          <Group18Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dVCaS
                            )}
                            role={"img"}
                          />

                          <Group19Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__taN4
                            )}
                            role={"img"}
                          />

                          <Group20Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___5V1Sh
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container164"}
                data-plasmic-override={overrides.container164}
                className={classNames(projectcss.all, sty.container164)}
              >
                <div
                  data-plasmic-name={"image62"}
                  data-plasmic-override={overrides.image62}
                  className={classNames(projectcss.all, sty.image62)}
                />

                <div
                  data-plasmic-name={"rectangle31"}
                  data-plasmic-override={overrides.rectangle31}
                  className={classNames(projectcss.all, sty.rectangle31)}
                />

                <div
                  data-plasmic-name={"expandYourWorld"}
                  data-plasmic-override={overrides.expandYourWorld}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.expandYourWorld
                  )}
                >
                  {"ClarityIQ"}
                </div>
                <Group21Icon
                  className={classNames(projectcss.all, sty.svg__dnpvv)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"sereneEscapesPodcast"}
                  data-plasmic-override={overrides.sereneEscapesPodcast}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.sereneEscapesPodcast
                  )}
                >
                  {"Business Clarity Analysis Platform"}
                </div>
              </div>
              <div
                data-plasmic-name={"container179"}
                data-plasmic-override={overrides.container179}
                className={classNames(projectcss.all, sty.container179)}
              >
                <div
                  data-plasmic-name={"image71"}
                  data-plasmic-override={overrides.image71}
                  className={classNames(projectcss.all, sty.image71)}
                />

                <div
                  data-plasmic-name={"button140"}
                  data-plasmic-override={overrides.button140}
                  className={classNames(projectcss.all, sty.button140)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wt9U
                    )}
                  >
                    {"LISTEN NOW"}
                  </div>
                  <ArrowRightIcon
                    className={classNames(projectcss.all, sty.svg__ruUwK)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"container180"}
                data-plasmic-override={overrides.container180}
                className={classNames(projectcss.all, sty.container180)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__maNEk
                  )}
                >
                  {"Our Community"}
                </div>
                <div
                  data-plasmic-name={"image72"}
                  data-plasmic-override={overrides.image72}
                  className={classNames(projectcss.all, sty.image72)}
                />

                <div
                  data-plasmic-name={"image73"}
                  data-plasmic-override={overrides.image73}
                  className={classNames(projectcss.all, sty.image73)}
                />

                <div
                  data-plasmic-name={"image74"}
                  data-plasmic-override={overrides.image74}
                  className={classNames(projectcss.all, sty.image74)}
                />

                <div
                  data-plasmic-name={"image75"}
                  data-plasmic-override={overrides.image75}
                  className={classNames(projectcss.all, sty.image75)}
                />

                <div
                  data-plasmic-name={"image76"}
                  data-plasmic-override={overrides.image76}
                  className={classNames(projectcss.all, sty.image76)}
                />

                <div
                  data-plasmic-name={"image77"}
                  data-plasmic-override={overrides.image77}
                  className={classNames(projectcss.all, sty.image77)}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "wireframe16",
    "newsListing",
    "container163",
    "dropdownButton8",
    "image61",
    "group",
    "group2",
    "group3",
    "group4",
    "container164",
    "image62",
    "rectangle31",
    "expandYourWorld",
    "sereneEscapesPodcast",
    "container179",
    "image71",
    "button140",
    "container180",
    "image72",
    "image73",
    "image74",
    "image75",
    "image76",
    "image77"
  ],
  wireframe16: [
    "wireframe16",
    "newsListing",
    "container163",
    "dropdownButton8",
    "image61",
    "group",
    "group2",
    "group3",
    "group4",
    "container164",
    "image62",
    "rectangle31",
    "expandYourWorld",
    "sereneEscapesPodcast",
    "container179",
    "image71",
    "button140",
    "container180",
    "image72",
    "image73",
    "image74",
    "image75",
    "image76",
    "image77"
  ],
  newsListing: [
    "newsListing",
    "container163",
    "dropdownButton8",
    "image61",
    "group",
    "group2",
    "group3",
    "group4",
    "container164",
    "image62",
    "rectangle31",
    "expandYourWorld",
    "sereneEscapesPodcast",
    "container179",
    "image71",
    "button140",
    "container180",
    "image72",
    "image73",
    "image74",
    "image75",
    "image76",
    "image77"
  ],
  container163: [
    "container163",
    "dropdownButton8",
    "image61",
    "group",
    "group2",
    "group3",
    "group4"
  ],
  dropdownButton8: ["dropdownButton8"],
  image61: ["image61", "group", "group2", "group3", "group4"],
  group: ["group", "group2", "group3", "group4"],
  group2: ["group2", "group3", "group4"],
  group3: ["group3", "group4"],
  group4: ["group4"],
  container164: [
    "container164",
    "image62",
    "rectangle31",
    "expandYourWorld",
    "sereneEscapesPodcast"
  ],
  image62: ["image62"],
  rectangle31: ["rectangle31"],
  expandYourWorld: ["expandYourWorld"],
  sereneEscapesPodcast: ["sereneEscapesPodcast"],
  container179: ["container179", "image71", "button140"],
  image71: ["image71"],
  button140: ["button140"],
  container180: [
    "container180",
    "image72",
    "image73",
    "image74",
    "image75",
    "image76",
    "image77"
  ],
  image72: ["image72"],
  image73: ["image73"],
  image74: ["image74"],
  image75: ["image75"],
  image76: ["image76"],
  image77: ["image77"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  wireframe16: "div";
  newsListing: "div";
  container163: "div";
  dropdownButton8: "div";
  image61: "div";
  group: "div";
  group2: "div";
  group3: "div";
  group4: "div";
  container164: "div";
  image62: "div";
  rectangle31: "div";
  expandYourWorld: "div";
  sereneEscapesPodcast: "div";
  container179: "div";
  image71: "div";
  button140: "div";
  container180: "div";
  image72: "div";
  image73: "div";
  image74: "div";
  image75: "div";
  image76: "div";
  image77: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOurcommunity__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOurcommunity__VariantsArgs;
    args?: PlasmicOurcommunity__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOurcommunity__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOurcommunity__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOurcommunity__ArgProps,
          internalVariantPropNames: PlasmicOurcommunity__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOurcommunity__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOurcommunity";
  } else {
    func.displayName = `PlasmicOurcommunity.${nodeName}`;
  }
  return func;
}

export const PlasmicOurcommunity = Object.assign(
  // Top-level PlasmicOurcommunity renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wireframe16: makeNodeComponent("wireframe16"),
    newsListing: makeNodeComponent("newsListing"),
    container163: makeNodeComponent("container163"),
    dropdownButton8: makeNodeComponent("dropdownButton8"),
    image61: makeNodeComponent("image61"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    container164: makeNodeComponent("container164"),
    image62: makeNodeComponent("image62"),
    rectangle31: makeNodeComponent("rectangle31"),
    expandYourWorld: makeNodeComponent("expandYourWorld"),
    sereneEscapesPodcast: makeNodeComponent("sereneEscapesPodcast"),
    container179: makeNodeComponent("container179"),
    image71: makeNodeComponent("image71"),
    button140: makeNodeComponent("button140"),
    container180: makeNodeComponent("container180"),
    image72: makeNodeComponent("image72"),
    image73: makeNodeComponent("image73"),
    image74: makeNodeComponent("image74"),
    image75: makeNodeComponent("image75"),
    image76: makeNodeComponent("image76"),
    image77: makeNodeComponent("image77"),

    // Metadata about props expected for PlasmicOurcommunity
    internalVariantProps: PlasmicOurcommunity__VariantProps,
    internalArgProps: PlasmicOurcommunity__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOurcommunity;
/* prettier-ignore-end */
