// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bVumzfkpaXXcvNmP8r5aNd
// Component: GXUwSSJc-WMF

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bVumzfkpaXXcvNmP8r5aNd/projectcss
import sty from "./PlasmicKpireports.module.css"; // plasmic-import: GXUwSSJc-WMF/css

import Group28Icon from "./icons/PlasmicIcon__Group28"; // plasmic-import: iMP_eYOq2_jl/icon
import Group29Icon from "./icons/PlasmicIcon__Group29"; // plasmic-import: K3N4dkayluwp/icon
import Group30Icon from "./icons/PlasmicIcon__Group30"; // plasmic-import: Ut7kKC-LXcxL/icon

createPlasmicElementProxy;

export type PlasmicKpireports__VariantMembers = {};
export type PlasmicKpireports__VariantsArgs = {};
type VariantPropType = keyof PlasmicKpireports__VariantsArgs;
export const PlasmicKpireports__VariantProps = new Array<VariantPropType>();

export type PlasmicKpireports__ArgsType = {};
type ArgPropType = keyof PlasmicKpireports__ArgsType;
export const PlasmicKpireports__ArgProps = new Array<ArgPropType>();

export type PlasmicKpireports__OverridesType = {
  root?: Flex__<"div">;
  wireframe2?: Flex__<"div">;
  conversionOutput?: Flex__<"div">;
  container83?: Flex__<"div">;
  container79?: Flex__<"div">;
  container72?: Flex__<"div">;
  container73?: Flex__<"div">;
  container70?: Flex__<"div">;
  container71?: Flex__<"div">;
  container69?: Flex__<"div">;
  issueType?: Flex__<"div">;
  container65?: Flex__<"div">;
  container66?: Flex__<"div">;
  container67?: Flex__<"div">;
  container68?: Flex__<"div">;
  container64?: Flex__<"div">;
  container63?: Flex__<"div">;
  ticketId?: Flex__<"div">;
  container59?: Flex__<"div">;
  _5?: Flex__<"div">;
  container60?: Flex__<"div">;
  _6?: Flex__<"div">;
  container61?: Flex__<"div">;
  _7?: Flex__<"div">;
  container62?: Flex__<"div">;
  _8?: Flex__<"div">;
  container58?: Flex__<"div">;
  image18?: Flex__<"div">;
  container57?: Flex__<"div">;
  container53?: Flex__<"div">;
  container54?: Flex__<"div">;
  container55?: Flex__<"div">;
  container56?: Flex__<"div">;
  container52?: Flex__<"div">;
  resolutionTimeHrs?: Flex__<"div">;
  container51?: Flex__<"div">;
  image16?: Flex__<"div">;
  _9?: Flex__<"div">;
  container47?: Flex__<"div">;
  container48?: Flex__<"div">;
  container49?: Flex__<"div">;
  container50?: Flex__<"div">;
  container45?: Flex__<"div">;
  container44?: Flex__<"div">;
  customerSatisfactionRating?: Flex__<"div">;
  container43?: Flex__<"div">;
  image6?: Flex__<"div">;
  container76?: Flex__<"div">;
  image20?: Flex__<"div">;
  group?: Flex__<"div">;
  group2?: Flex__<"div">;
  group3?: Flex__<"div">;
  group4?: Flex__<"div">;
  tag23?: Flex__<"div">;
  frame?: Flex__<"div">;
  tag22?: Flex__<"div">;
  frame2?: Flex__<"div">;
  tag21?: Flex__<"div">;
  frame3?: Flex__<"div">;
  newMarketingReportKip?: Flex__<"div">;
  newOperationReportKip?: Flex__<"div">;
  newCustomerServiceKpiReportTotal?: Flex__<"div">;
  reportNewOperationReport?: Flex__<"div">;
  sumOfCrewMembers?: Flex__<"div">;
  checkbox12?: Flex__<"div">;
  frame4?: Flex__<"div">;
  rectangle?: Flex__<"div">;
  image5?: Flex__<"div">;
  image8?: Flex__<"div">;
  image12?: Flex__<"div">;
  container100?: Flex__<"div">;
  rectangle63?: Flex__<"div">;
  container101?: Flex__<"div">;
  rectangle64?: Flex__<"div">;
  container102?: Flex__<"div">;
  rectangle65?: Flex__<"div">;
  container82?: Flex__<"div">;
  container77?: Flex__<"div">;
  container75?: Flex__<"div">;
  container78?: Flex__<"div">;
  container80?: Flex__<"div">;
  newFinanceReportKip?: Flex__<"div">;
  viewReportNewFinanceReport?: Flex__<"div">;
  yuliyasStarship?: Flex__<"div">;
  someStarship?: Flex__<"div">;
  image9?: Flex__<"div">;
  image13?: Flex__<"div">;
  image11?: Flex__<"div">;
  someStarship2?: Flex__<"div">;
  container81?: Flex__<"div">;
  image7?: Flex__<"div">;
  image17?: Flex__<"div">;
  container84?: Flex__<"div">;
  image10?: Flex__<"div">;
  newSalesKpiReportTotal2?: Flex__<"div">;
  container85?: Flex__<"div">;
  headerMenu1?: Flex__<"div">;
  frame5?: Flex__<"div">;
  frame6?: Flex__<"div">;
  frame7?: Flex__<"div">;
  image14?: Flex__<"div">;
};

export interface DefaultKpireportsProps {
  className?: string;
}

const $$ = {};

function PlasmicKpireports__RenderFunc(props: {
  variants: PlasmicKpireports__VariantsArgs;
  args: PlasmicKpireports__ArgsType;
  overrides: PlasmicKpireports__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"wireframe2"}
        data-plasmic-override={overrides.wireframe2}
        className={classNames(projectcss.all, sty.wireframe2)}
      >
        <div
          data-plasmic-name={"conversionOutput"}
          data-plasmic-override={overrides.conversionOutput}
          className={classNames(projectcss.all, sty.conversionOutput)}
        >
          <div
            data-plasmic-name={"container83"}
            data-plasmic-override={overrides.container83}
            className={classNames(projectcss.all, sty.container83)}
          >
            <div
              data-plasmic-name={"container79"}
              data-plasmic-override={overrides.container79}
              className={classNames(projectcss.all, sty.container79)}
            >
              <div
                data-plasmic-name={"container72"}
                data-plasmic-override={overrides.container72}
                className={classNames(projectcss.all, sty.container72)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qvRqV
                  )}
                >
                  {"Product Defect\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container73"}
                data-plasmic-override={overrides.container73}
                className={classNames(projectcss.all, sty.container73)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fx7Br
                  )}
                >
                  {"Billing Inquiry\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container70"}
                data-plasmic-override={overrides.container70}
                className={classNames(projectcss.all, sty.container70)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ezAjM
                  )}
                >
                  {"Shipping Delay\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container71"}
                data-plasmic-override={overrides.container71}
                className={classNames(projectcss.all, sty.container71)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nge0P
                  )}
                >
                  {"Technical Support\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container69"}
                data-plasmic-override={overrides.container69}
                className={classNames(projectcss.all, sty.container69)}
              >
                <div
                  data-plasmic-name={"issueType"}
                  data-plasmic-override={overrides.issueType}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.issueType
                  )}
                >
                  {"Interactive Elements"}
                </div>
              </div>
              <div
                data-plasmic-name={"container65"}
                data-plasmic-override={overrides.container65}
                className={classNames(projectcss.all, sty.container65)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tQk6
                  )}
                >
                  {"101\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container66"}
                data-plasmic-override={overrides.container66}
                className={classNames(projectcss.all, sty.container66)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hIx8H
                  )}
                >
                  {"102\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container67"}
                data-plasmic-override={overrides.container67}
                className={classNames(projectcss.all, sty.container67)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0YNs
                  )}
                >
                  {"103"}
                </div>
              </div>
              <div
                data-plasmic-name={"container68"}
                data-plasmic-override={overrides.container68}
                className={classNames(projectcss.all, sty.container68)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__peVZo
                  )}
                >
                  {"104"}
                </div>
              </div>
              <div
                data-plasmic-name={"container64"}
                data-plasmic-override={overrides.container64}
                className={classNames(projectcss.all, sty.container64)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gTgY
                  )}
                >
                  {"Account Issue\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"container63"}
                data-plasmic-override={overrides.container63}
                className={classNames(projectcss.all, sty.container63)}
              >
                <div
                  data-plasmic-name={"ticketId"}
                  data-plasmic-override={overrides.ticketId}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.ticketId
                  )}
                >
                  {"#"}
                </div>
              </div>
              <div
                data-plasmic-name={"container59"}
                data-plasmic-override={overrides.container59}
                className={classNames(projectcss.all, sty.container59)}
              >
                <div
                  data-plasmic-name={"_5"}
                  data-plasmic-override={overrides._5}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._5
                  )}
                >
                  {"56%"}
                </div>
              </div>
              <div
                data-plasmic-name={"container60"}
                data-plasmic-override={overrides.container60}
                className={classNames(projectcss.all, sty.container60)}
              >
                <div
                  data-plasmic-name={"_6"}
                  data-plasmic-override={overrides._6}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._6
                  )}
                >
                  {"53%"}
                </div>
              </div>
              <div
                data-plasmic-name={"container61"}
                data-plasmic-override={overrides.container61}
                className={classNames(projectcss.all, sty.container61)}
              >
                <div
                  data-plasmic-name={"_7"}
                  data-plasmic-override={overrides._7}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._7
                  )}
                >
                  {"97%"}
                </div>
              </div>
              <div
                data-plasmic-name={"container62"}
                data-plasmic-override={overrides.container62}
                className={classNames(projectcss.all, sty.container62)}
              >
                <div
                  data-plasmic-name={"_8"}
                  data-plasmic-override={overrides._8}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._8
                  )}
                >
                  {"14%"}
                </div>
              </div>
              <div
                data-plasmic-name={"container58"}
                data-plasmic-override={overrides.container58}
                className={classNames(projectcss.all, sty.container58)}
              >
                <div
                  data-plasmic-name={"image18"}
                  data-plasmic-override={overrides.image18}
                  className={classNames(projectcss.all, sty.image18)}
                />
              </div>
              <div
                data-plasmic-name={"container57"}
                data-plasmic-override={overrides.container57}
                className={classNames(projectcss.all, sty.container57)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cok1U
                  )}
                >
                  {"105"}
                </div>
              </div>
              <div
                data-plasmic-name={"container53"}
                data-plasmic-override={overrides.container53}
                className={classNames(projectcss.all, sty.container53)}
              />

              <div
                data-plasmic-name={"container54"}
                data-plasmic-override={overrides.container54}
                className={classNames(projectcss.all, sty.container54)}
              />

              <div
                data-plasmic-name={"container55"}
                data-plasmic-override={overrides.container55}
                className={classNames(projectcss.all, sty.container55)}
              />

              <div
                data-plasmic-name={"container56"}
                data-plasmic-override={overrides.container56}
                className={classNames(projectcss.all, sty.container56)}
              />

              <div
                data-plasmic-name={"container52"}
                data-plasmic-override={overrides.container52}
                className={classNames(projectcss.all, sty.container52)}
              >
                <div
                  data-plasmic-name={"resolutionTimeHrs"}
                  data-plasmic-override={overrides.resolutionTimeHrs}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.resolutionTimeHrs
                  )}
                >
                  {"Actionable \nReports"}
                </div>
              </div>
              <div
                data-plasmic-name={"container51"}
                data-plasmic-override={overrides.container51}
                className={classNames(projectcss.all, sty.container51)}
              >
                <div
                  data-plasmic-name={"image16"}
                  data-plasmic-override={overrides.image16}
                  className={classNames(projectcss.all, sty.image16)}
                />

                <div
                  data-plasmic-name={"_9"}
                  data-plasmic-override={overrides._9}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._9
                  )}
                >
                  {"14%"}
                </div>
              </div>
              <div
                data-plasmic-name={"container47"}
                data-plasmic-override={overrides.container47}
                className={classNames(projectcss.all, sty.container47)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5T9Lu
                  )}
                >
                  {"3"}
                </div>
              </div>
              <div
                data-plasmic-name={"container48"}
                data-plasmic-override={overrides.container48}
                className={classNames(projectcss.all, sty.container48)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9HUxE
                  )}
                >
                  {"3"}
                </div>
              </div>
              <div
                data-plasmic-name={"container49"}
                data-plasmic-override={overrides.container49}
                className={classNames(projectcss.all, sty.container49)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cGfUr
                  )}
                >
                  {"3"}
                </div>
              </div>
              <div
                data-plasmic-name={"container50"}
                data-plasmic-override={overrides.container50}
                className={classNames(projectcss.all, sty.container50)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9MbXw
                  )}
                >
                  {"3"}
                </div>
              </div>
              <div
                data-plasmic-name={"container45"}
                data-plasmic-override={overrides.container45}
                className={classNames(projectcss.all, sty.container45)}
              />

              <div
                data-plasmic-name={"container44"}
                data-plasmic-override={overrides.container44}
                className={classNames(projectcss.all, sty.container44)}
              >
                <div
                  data-plasmic-name={"customerSatisfactionRating"}
                  data-plasmic-override={overrides.customerSatisfactionRating}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.customerSatisfactionRating
                  )}
                >
                  {"Insight Generation"}
                </div>
              </div>
              <div
                data-plasmic-name={"container43"}
                data-plasmic-override={overrides.container43}
                className={classNames(projectcss.all, sty.container43)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eTYj2
                  )}
                >
                  {"3"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"image6"}
              data-plasmic-override={overrides.image6}
              className={classNames(projectcss.all, sty.image6)}
            />

            <div
              data-plasmic-name={"container76"}
              data-plasmic-override={overrides.container76}
              className={classNames(projectcss.all, sty.container76)}
            >
              <div
                data-plasmic-name={"image20"}
                data-plasmic-override={overrides.image20}
                className={classNames(projectcss.all, sty.image20)}
              >
                <div
                  data-plasmic-name={"group"}
                  data-plasmic-override={overrides.group}
                  className={classNames(projectcss.all, sty.group)}
                >
                  <div
                    data-plasmic-name={"group2"}
                    data-plasmic-override={overrides.group2}
                    className={classNames(projectcss.all, sty.group2)}
                  >
                    <div
                      data-plasmic-name={"group3"}
                      data-plasmic-override={overrides.group3}
                      className={classNames(projectcss.all, sty.group3)}
                    >
                      <div
                        data-plasmic-name={"group4"}
                        data-plasmic-override={overrides.group4}
                        className={classNames(projectcss.all, sty.group4)}
                      >
                        <Group28Icon
                          className={classNames(projectcss.all, sty.svg__xfVyi)}
                          role={"img"}
                        />

                        <Group29Icon
                          className={classNames(projectcss.all, sty.svg__yq3T9)}
                          role={"img"}
                        />

                        <Group30Icon
                          className={classNames(projectcss.all, sty.svg__vHwK5)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"tag23"}
                data-plasmic-override={overrides.tag23}
                className={classNames(projectcss.all, sty.tag23)}
              >
                <div
                  data-plasmic-name={"frame"}
                  data-plasmic-override={overrides.frame}
                  className={classNames(projectcss.all, sty.frame)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qBvr6
                    )}
                  >
                    {"5%"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"tag22"}
                data-plasmic-override={overrides.tag22}
                className={classNames(projectcss.all, sty.tag22)}
              >
                <div
                  data-plasmic-name={"frame2"}
                  data-plasmic-override={overrides.frame2}
                  className={classNames(projectcss.all, sty.frame2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fKqEo
                    )}
                  >
                    {"20.5%"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"tag21"}
                data-plasmic-override={overrides.tag21}
                className={classNames(projectcss.all, sty.tag21)}
              >
                <div
                  data-plasmic-name={"frame3"}
                  data-plasmic-override={overrides.frame3}
                  className={classNames(projectcss.all, sty.frame3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9Vbvm
                    )}
                  >
                    {"100%"}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"newMarketingReportKip"}
              data-plasmic-override={overrides.newMarketingReportKip}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.newMarketingReportKip
              )}
            >
              {"Anomaly Detection: Report KIP"}
            </div>
            <div
              data-plasmic-name={"newOperationReportKip"}
              data-plasmic-override={overrides.newOperationReportKip}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.newOperationReportKip
              )}
            >
              {"Trend Analysis KIP"}
            </div>
            <div
              data-plasmic-name={"newCustomerServiceKpiReportTotal"}
              data-plasmic-override={overrides.newCustomerServiceKpiReportTotal}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.newCustomerServiceKpiReportTotal
              )}
            >
              {"Data-Driven Insights KPI Report total"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qPeX
              )}
            >
              {"View Report (New Marketing Report )"}
            </div>
            <div
              data-plasmic-name={"reportNewOperationReport"}
              data-plasmic-override={overrides.reportNewOperationReport}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.reportNewOperationReport
              )}
            >
              {" Report (New Trends operations )"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2ZnX5
              )}
            >
              {"View Report (New Starships KPI Report total 2)"}
            </div>
            <div
              data-plasmic-name={"sumOfCrewMembers"}
              data-plasmic-override={overrides.sumOfCrewMembers}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.sumOfCrewMembers
              )}
            >
              {"Sum of Trend"}
            </div>
            <div
              data-plasmic-name={"checkbox12"}
              data-plasmic-override={overrides.checkbox12}
              className={classNames(projectcss.all, sty.checkbox12)}
            >
              <div
                data-plasmic-name={"frame4"}
                data-plasmic-override={overrides.frame4}
                className={classNames(projectcss.all, sty.frame4)}
              >
                <div
                  data-plasmic-name={"rectangle"}
                  data-plasmic-override={overrides.rectangle}
                  className={classNames(projectcss.all, sty.rectangle)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"image5"}
              data-plasmic-override={overrides.image5}
              className={classNames(projectcss.all, sty.image5)}
            />

            <div
              data-plasmic-name={"image8"}
              data-plasmic-override={overrides.image8}
              className={classNames(projectcss.all, sty.image8)}
            />

            <div
              data-plasmic-name={"image12"}
              data-plasmic-override={overrides.image12}
              className={classNames(projectcss.all, sty.image12)}
            />

            <div
              data-plasmic-name={"container100"}
              data-plasmic-override={overrides.container100}
              className={classNames(projectcss.all, sty.container100)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hSaFa
                )}
              >
                {"Prospects"}
              </div>
              <div
                data-plasmic-name={"rectangle63"}
                data-plasmic-override={overrides.rectangle63}
                className={classNames(projectcss.all, sty.rectangle63)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uroxG
                )}
              >
                {"200"}
              </div>
            </div>
            <div
              data-plasmic-name={"container101"}
              data-plasmic-override={overrides.container101}
              className={classNames(projectcss.all, sty.container101)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wklsc
                )}
              >
                {"Opportunities"}
              </div>
              <div
                data-plasmic-name={"rectangle64"}
                data-plasmic-override={overrides.rectangle64}
                className={classNames(projectcss.all, sty.rectangle64)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__voeys
                )}
              >
                {"41"}
              </div>
            </div>
            <div
              data-plasmic-name={"container102"}
              data-plasmic-override={overrides.container102}
              className={classNames(projectcss.all, sty.container102)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kbAjk
                )}
              >
                {"Negotiation"}
              </div>
              <div
                data-plasmic-name={"rectangle65"}
                data-plasmic-override={overrides.rectangle65}
                className={classNames(projectcss.all, sty.rectangle65)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__evLh7
                )}
              >
                {"10"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"container82"}
            data-plasmic-override={overrides.container82}
            className={classNames(projectcss.all, sty.container82)}
          >
            <div
              data-plasmic-name={"container77"}
              data-plasmic-override={overrides.container77}
              className={classNames(projectcss.all, sty.container77)}
            >
              <div
                data-plasmic-name={"container75"}
                data-plasmic-override={overrides.container75}
                className={classNames(projectcss.all, sty.container75)}
              />

              <div
                data-plasmic-name={"container78"}
                data-plasmic-override={overrides.container78}
                className={classNames(projectcss.all, sty.container78)}
              />

              <div
                data-plasmic-name={"container80"}
                data-plasmic-override={overrides.container80}
                className={classNames(projectcss.all, sty.container80)}
              />
            </div>
            <div
              data-plasmic-name={"newFinanceReportKip"}
              data-plasmic-override={overrides.newFinanceReportKip}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.newFinanceReportKip
              )}
            >
              {"Performance Tracking KPI"}
            </div>
            <div
              data-plasmic-name={"viewReportNewFinanceReport"}
              data-plasmic-override={overrides.viewReportNewFinanceReport}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.viewReportNewFinanceReport
              )}
            >
              {"View Report (New performance Report"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4Dp58
              )}
            >
              {"Sum of  Members"}
            </div>
            <div
              data-plasmic-name={"yuliyasStarship"}
              data-plasmic-override={overrides.yuliyasStarship}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.yuliyasStarship
              )}
            >
              {"Week 3"}
            </div>
            <div
              data-plasmic-name={"someStarship"}
              data-plasmic-override={overrides.someStarship}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.someStarship
              )}
            >
              {"Week 1"}
            </div>
            <div
              data-plasmic-name={"image9"}
              data-plasmic-override={overrides.image9}
              className={classNames(projectcss.all, sty.image9)}
            />

            <div
              data-plasmic-name={"image13"}
              data-plasmic-override={overrides.image13}
              className={classNames(projectcss.all, sty.image13)}
            />

            <div
              data-plasmic-name={"image11"}
              data-plasmic-override={overrides.image11}
              className={classNames(projectcss.all, sty.image11)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bY04
              )}
            >
              {"3"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mnye3
              )}
            >
              {"2"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oiyOj
              )}
            >
              {"0"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1Ld5M
              )}
            >
              {"6"}
            </div>
            <div
              data-plasmic-name={"someStarship2"}
              data-plasmic-override={overrides.someStarship2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.someStarship2
              )}
            >
              {"Week 2"}
            </div>
          </div>
          <div
            data-plasmic-name={"container81"}
            data-plasmic-override={overrides.container81}
            className={classNames(projectcss.all, sty.container81)}
          >
            <div
              data-plasmic-name={"image7"}
              data-plasmic-override={overrides.image7}
              className={classNames(projectcss.all, sty.image7)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jHacL
              )}
            >
              {"New Sales KPI Report total 2"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1AiXn
              )}
            >
              {"View Report (New Sales KPI Report total 2)"}
            </div>
            <div
              data-plasmic-name={"image17"}
              data-plasmic-override={overrides.image17}
              className={classNames(projectcss.all, sty.image17)}
            />
          </div>
          <div
            data-plasmic-name={"container84"}
            data-plasmic-override={overrides.container84}
            className={classNames(projectcss.all, sty.container84)}
          >
            <div
              data-plasmic-name={"image10"}
              data-plasmic-override={overrides.image10}
              className={classNames(projectcss.all, sty.image10)}
            />

            <div
              data-plasmic-name={"newSalesKpiReportTotal2"}
              data-plasmic-override={overrides.newSalesKpiReportTotal2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.newSalesKpiReportTotal2
              )}
            >
              {" KPI Report total 2"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___83J
              )}
            >
              {"View Report (New Starships KPI Report total 2)"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___6QrJd
              )}
            >
              {"%"}
            </div>
          </div>
          <div
            data-plasmic-name={"container85"}
            data-plasmic-override={overrides.container85}
            className={classNames(projectcss.all, sty.container85)}
          >
            <div
              data-plasmic-name={"headerMenu1"}
              data-plasmic-override={overrides.headerMenu1}
              className={classNames(projectcss.all, sty.headerMenu1)}
            >
              <div
                data-plasmic-name={"frame5"}
                data-plasmic-override={overrides.frame5}
                className={classNames(projectcss.all, sty.frame5)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cnFqj
                  )}
                >
                  {"Open"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame6"}
                data-plasmic-override={overrides.frame6}
                className={classNames(projectcss.all, sty.frame6)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4AK2E
                  )}
                >
                  {"Refresh"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                className={classNames(projectcss.all, sty.frame7)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__daoFr
                  )}
                >
                  {"Subscribe"}
                </div>
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9SQYc
              )}
            >
              {"As of 14 Aug 2023, 18:56-Viewing as Dorian Sabitov"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gtB4D
              )}
            >
              {"Starships"}
            </div>
            <div
              data-plasmic-name={"image14"}
              data-plasmic-override={overrides.image14}
              className={classNames(projectcss.all, sty.image14)}
            />
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "wireframe2",
    "conversionOutput",
    "container83",
    "container79",
    "container72",
    "container73",
    "container70",
    "container71",
    "container69",
    "issueType",
    "container65",
    "container66",
    "container67",
    "container68",
    "container64",
    "container63",
    "ticketId",
    "container59",
    "_5",
    "container60",
    "_6",
    "container61",
    "_7",
    "container62",
    "_8",
    "container58",
    "image18",
    "container57",
    "container53",
    "container54",
    "container55",
    "container56",
    "container52",
    "resolutionTimeHrs",
    "container51",
    "image16",
    "_9",
    "container47",
    "container48",
    "container49",
    "container50",
    "container45",
    "container44",
    "customerSatisfactionRating",
    "container43",
    "image6",
    "container76",
    "image20",
    "group",
    "group2",
    "group3",
    "group4",
    "tag23",
    "frame",
    "tag22",
    "frame2",
    "tag21",
    "frame3",
    "newMarketingReportKip",
    "newOperationReportKip",
    "newCustomerServiceKpiReportTotal",
    "reportNewOperationReport",
    "sumOfCrewMembers",
    "checkbox12",
    "frame4",
    "rectangle",
    "image5",
    "image8",
    "image12",
    "container100",
    "rectangle63",
    "container101",
    "rectangle64",
    "container102",
    "rectangle65",
    "container82",
    "container77",
    "container75",
    "container78",
    "container80",
    "newFinanceReportKip",
    "viewReportNewFinanceReport",
    "yuliyasStarship",
    "someStarship",
    "image9",
    "image13",
    "image11",
    "someStarship2",
    "container81",
    "image7",
    "image17",
    "container84",
    "image10",
    "newSalesKpiReportTotal2",
    "container85",
    "headerMenu1",
    "frame5",
    "frame6",
    "frame7",
    "image14"
  ],
  wireframe2: [
    "wireframe2",
    "conversionOutput",
    "container83",
    "container79",
    "container72",
    "container73",
    "container70",
    "container71",
    "container69",
    "issueType",
    "container65",
    "container66",
    "container67",
    "container68",
    "container64",
    "container63",
    "ticketId",
    "container59",
    "_5",
    "container60",
    "_6",
    "container61",
    "_7",
    "container62",
    "_8",
    "container58",
    "image18",
    "container57",
    "container53",
    "container54",
    "container55",
    "container56",
    "container52",
    "resolutionTimeHrs",
    "container51",
    "image16",
    "_9",
    "container47",
    "container48",
    "container49",
    "container50",
    "container45",
    "container44",
    "customerSatisfactionRating",
    "container43",
    "image6",
    "container76",
    "image20",
    "group",
    "group2",
    "group3",
    "group4",
    "tag23",
    "frame",
    "tag22",
    "frame2",
    "tag21",
    "frame3",
    "newMarketingReportKip",
    "newOperationReportKip",
    "newCustomerServiceKpiReportTotal",
    "reportNewOperationReport",
    "sumOfCrewMembers",
    "checkbox12",
    "frame4",
    "rectangle",
    "image5",
    "image8",
    "image12",
    "container100",
    "rectangle63",
    "container101",
    "rectangle64",
    "container102",
    "rectangle65",
    "container82",
    "container77",
    "container75",
    "container78",
    "container80",
    "newFinanceReportKip",
    "viewReportNewFinanceReport",
    "yuliyasStarship",
    "someStarship",
    "image9",
    "image13",
    "image11",
    "someStarship2",
    "container81",
    "image7",
    "image17",
    "container84",
    "image10",
    "newSalesKpiReportTotal2",
    "container85",
    "headerMenu1",
    "frame5",
    "frame6",
    "frame7",
    "image14"
  ],
  conversionOutput: [
    "conversionOutput",
    "container83",
    "container79",
    "container72",
    "container73",
    "container70",
    "container71",
    "container69",
    "issueType",
    "container65",
    "container66",
    "container67",
    "container68",
    "container64",
    "container63",
    "ticketId",
    "container59",
    "_5",
    "container60",
    "_6",
    "container61",
    "_7",
    "container62",
    "_8",
    "container58",
    "image18",
    "container57",
    "container53",
    "container54",
    "container55",
    "container56",
    "container52",
    "resolutionTimeHrs",
    "container51",
    "image16",
    "_9",
    "container47",
    "container48",
    "container49",
    "container50",
    "container45",
    "container44",
    "customerSatisfactionRating",
    "container43",
    "image6",
    "container76",
    "image20",
    "group",
    "group2",
    "group3",
    "group4",
    "tag23",
    "frame",
    "tag22",
    "frame2",
    "tag21",
    "frame3",
    "newMarketingReportKip",
    "newOperationReportKip",
    "newCustomerServiceKpiReportTotal",
    "reportNewOperationReport",
    "sumOfCrewMembers",
    "checkbox12",
    "frame4",
    "rectangle",
    "image5",
    "image8",
    "image12",
    "container100",
    "rectangle63",
    "container101",
    "rectangle64",
    "container102",
    "rectangle65",
    "container82",
    "container77",
    "container75",
    "container78",
    "container80",
    "newFinanceReportKip",
    "viewReportNewFinanceReport",
    "yuliyasStarship",
    "someStarship",
    "image9",
    "image13",
    "image11",
    "someStarship2",
    "container81",
    "image7",
    "image17",
    "container84",
    "image10",
    "newSalesKpiReportTotal2",
    "container85",
    "headerMenu1",
    "frame5",
    "frame6",
    "frame7",
    "image14"
  ],
  container83: [
    "container83",
    "container79",
    "container72",
    "container73",
    "container70",
    "container71",
    "container69",
    "issueType",
    "container65",
    "container66",
    "container67",
    "container68",
    "container64",
    "container63",
    "ticketId",
    "container59",
    "_5",
    "container60",
    "_6",
    "container61",
    "_7",
    "container62",
    "_8",
    "container58",
    "image18",
    "container57",
    "container53",
    "container54",
    "container55",
    "container56",
    "container52",
    "resolutionTimeHrs",
    "container51",
    "image16",
    "_9",
    "container47",
    "container48",
    "container49",
    "container50",
    "container45",
    "container44",
    "customerSatisfactionRating",
    "container43",
    "image6",
    "container76",
    "image20",
    "group",
    "group2",
    "group3",
    "group4",
    "tag23",
    "frame",
    "tag22",
    "frame2",
    "tag21",
    "frame3",
    "newMarketingReportKip",
    "newOperationReportKip",
    "newCustomerServiceKpiReportTotal",
    "reportNewOperationReport",
    "sumOfCrewMembers",
    "checkbox12",
    "frame4",
    "rectangle",
    "image5",
    "image8",
    "image12",
    "container100",
    "rectangle63",
    "container101",
    "rectangle64",
    "container102",
    "rectangle65"
  ],
  container79: [
    "container79",
    "container72",
    "container73",
    "container70",
    "container71",
    "container69",
    "issueType",
    "container65",
    "container66",
    "container67",
    "container68",
    "container64",
    "container63",
    "ticketId",
    "container59",
    "_5",
    "container60",
    "_6",
    "container61",
    "_7",
    "container62",
    "_8",
    "container58",
    "image18",
    "container57",
    "container53",
    "container54",
    "container55",
    "container56",
    "container52",
    "resolutionTimeHrs",
    "container51",
    "image16",
    "_9",
    "container47",
    "container48",
    "container49",
    "container50",
    "container45",
    "container44",
    "customerSatisfactionRating",
    "container43"
  ],
  container72: ["container72"],
  container73: ["container73"],
  container70: ["container70"],
  container71: ["container71"],
  container69: ["container69", "issueType"],
  issueType: ["issueType"],
  container65: ["container65"],
  container66: ["container66"],
  container67: ["container67"],
  container68: ["container68"],
  container64: ["container64"],
  container63: ["container63", "ticketId"],
  ticketId: ["ticketId"],
  container59: ["container59", "_5"],
  _5: ["_5"],
  container60: ["container60", "_6"],
  _6: ["_6"],
  container61: ["container61", "_7"],
  _7: ["_7"],
  container62: ["container62", "_8"],
  _8: ["_8"],
  container58: ["container58", "image18"],
  image18: ["image18"],
  container57: ["container57"],
  container53: ["container53"],
  container54: ["container54"],
  container55: ["container55"],
  container56: ["container56"],
  container52: ["container52", "resolutionTimeHrs"],
  resolutionTimeHrs: ["resolutionTimeHrs"],
  container51: ["container51", "image16", "_9"],
  image16: ["image16"],
  _9: ["_9"],
  container47: ["container47"],
  container48: ["container48"],
  container49: ["container49"],
  container50: ["container50"],
  container45: ["container45"],
  container44: ["container44", "customerSatisfactionRating"],
  customerSatisfactionRating: ["customerSatisfactionRating"],
  container43: ["container43"],
  image6: ["image6"],
  container76: [
    "container76",
    "image20",
    "group",
    "group2",
    "group3",
    "group4",
    "tag23",
    "frame",
    "tag22",
    "frame2",
    "tag21",
    "frame3"
  ],
  image20: ["image20", "group", "group2", "group3", "group4"],
  group: ["group", "group2", "group3", "group4"],
  group2: ["group2", "group3", "group4"],
  group3: ["group3", "group4"],
  group4: ["group4"],
  tag23: ["tag23", "frame"],
  frame: ["frame"],
  tag22: ["tag22", "frame2"],
  frame2: ["frame2"],
  tag21: ["tag21", "frame3"],
  frame3: ["frame3"],
  newMarketingReportKip: ["newMarketingReportKip"],
  newOperationReportKip: ["newOperationReportKip"],
  newCustomerServiceKpiReportTotal: ["newCustomerServiceKpiReportTotal"],
  reportNewOperationReport: ["reportNewOperationReport"],
  sumOfCrewMembers: ["sumOfCrewMembers"],
  checkbox12: ["checkbox12", "frame4", "rectangle"],
  frame4: ["frame4", "rectangle"],
  rectangle: ["rectangle"],
  image5: ["image5"],
  image8: ["image8"],
  image12: ["image12"],
  container100: ["container100", "rectangle63"],
  rectangle63: ["rectangle63"],
  container101: ["container101", "rectangle64"],
  rectangle64: ["rectangle64"],
  container102: ["container102", "rectangle65"],
  rectangle65: ["rectangle65"],
  container82: [
    "container82",
    "container77",
    "container75",
    "container78",
    "container80",
    "newFinanceReportKip",
    "viewReportNewFinanceReport",
    "yuliyasStarship",
    "someStarship",
    "image9",
    "image13",
    "image11",
    "someStarship2"
  ],
  container77: ["container77", "container75", "container78", "container80"],
  container75: ["container75"],
  container78: ["container78"],
  container80: ["container80"],
  newFinanceReportKip: ["newFinanceReportKip"],
  viewReportNewFinanceReport: ["viewReportNewFinanceReport"],
  yuliyasStarship: ["yuliyasStarship"],
  someStarship: ["someStarship"],
  image9: ["image9"],
  image13: ["image13"],
  image11: ["image11"],
  someStarship2: ["someStarship2"],
  container81: ["container81", "image7", "image17"],
  image7: ["image7"],
  image17: ["image17"],
  container84: ["container84", "image10", "newSalesKpiReportTotal2"],
  image10: ["image10"],
  newSalesKpiReportTotal2: ["newSalesKpiReportTotal2"],
  container85: [
    "container85",
    "headerMenu1",
    "frame5",
    "frame6",
    "frame7",
    "image14"
  ],
  headerMenu1: ["headerMenu1", "frame5", "frame6", "frame7"],
  frame5: ["frame5"],
  frame6: ["frame6"],
  frame7: ["frame7"],
  image14: ["image14"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  wireframe2: "div";
  conversionOutput: "div";
  container83: "div";
  container79: "div";
  container72: "div";
  container73: "div";
  container70: "div";
  container71: "div";
  container69: "div";
  issueType: "div";
  container65: "div";
  container66: "div";
  container67: "div";
  container68: "div";
  container64: "div";
  container63: "div";
  ticketId: "div";
  container59: "div";
  _5: "div";
  container60: "div";
  _6: "div";
  container61: "div";
  _7: "div";
  container62: "div";
  _8: "div";
  container58: "div";
  image18: "div";
  container57: "div";
  container53: "div";
  container54: "div";
  container55: "div";
  container56: "div";
  container52: "div";
  resolutionTimeHrs: "div";
  container51: "div";
  image16: "div";
  _9: "div";
  container47: "div";
  container48: "div";
  container49: "div";
  container50: "div";
  container45: "div";
  container44: "div";
  customerSatisfactionRating: "div";
  container43: "div";
  image6: "div";
  container76: "div";
  image20: "div";
  group: "div";
  group2: "div";
  group3: "div";
  group4: "div";
  tag23: "div";
  frame: "div";
  tag22: "div";
  frame2: "div";
  tag21: "div";
  frame3: "div";
  newMarketingReportKip: "div";
  newOperationReportKip: "div";
  newCustomerServiceKpiReportTotal: "div";
  reportNewOperationReport: "div";
  sumOfCrewMembers: "div";
  checkbox12: "div";
  frame4: "div";
  rectangle: "div";
  image5: "div";
  image8: "div";
  image12: "div";
  container100: "div";
  rectangle63: "div";
  container101: "div";
  rectangle64: "div";
  container102: "div";
  rectangle65: "div";
  container82: "div";
  container77: "div";
  container75: "div";
  container78: "div";
  container80: "div";
  newFinanceReportKip: "div";
  viewReportNewFinanceReport: "div";
  yuliyasStarship: "div";
  someStarship: "div";
  image9: "div";
  image13: "div";
  image11: "div";
  someStarship2: "div";
  container81: "div";
  image7: "div";
  image17: "div";
  container84: "div";
  image10: "div";
  newSalesKpiReportTotal2: "div";
  container85: "div";
  headerMenu1: "div";
  frame5: "div";
  frame6: "div";
  frame7: "div";
  image14: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicKpireports__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicKpireports__VariantsArgs;
    args?: PlasmicKpireports__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicKpireports__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicKpireports__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicKpireports__ArgProps,
          internalVariantPropNames: PlasmicKpireports__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicKpireports__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicKpireports";
  } else {
    func.displayName = `PlasmicKpireports.${nodeName}`;
  }
  return func;
}

export const PlasmicKpireports = Object.assign(
  // Top-level PlasmicKpireports renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wireframe2: makeNodeComponent("wireframe2"),
    conversionOutput: makeNodeComponent("conversionOutput"),
    container83: makeNodeComponent("container83"),
    container79: makeNodeComponent("container79"),
    container72: makeNodeComponent("container72"),
    container73: makeNodeComponent("container73"),
    container70: makeNodeComponent("container70"),
    container71: makeNodeComponent("container71"),
    container69: makeNodeComponent("container69"),
    issueType: makeNodeComponent("issueType"),
    container65: makeNodeComponent("container65"),
    container66: makeNodeComponent("container66"),
    container67: makeNodeComponent("container67"),
    container68: makeNodeComponent("container68"),
    container64: makeNodeComponent("container64"),
    container63: makeNodeComponent("container63"),
    ticketId: makeNodeComponent("ticketId"),
    container59: makeNodeComponent("container59"),
    _5: makeNodeComponent("_5"),
    container60: makeNodeComponent("container60"),
    _6: makeNodeComponent("_6"),
    container61: makeNodeComponent("container61"),
    _7: makeNodeComponent("_7"),
    container62: makeNodeComponent("container62"),
    _8: makeNodeComponent("_8"),
    container58: makeNodeComponent("container58"),
    image18: makeNodeComponent("image18"),
    container57: makeNodeComponent("container57"),
    container53: makeNodeComponent("container53"),
    container54: makeNodeComponent("container54"),
    container55: makeNodeComponent("container55"),
    container56: makeNodeComponent("container56"),
    container52: makeNodeComponent("container52"),
    resolutionTimeHrs: makeNodeComponent("resolutionTimeHrs"),
    container51: makeNodeComponent("container51"),
    image16: makeNodeComponent("image16"),
    _9: makeNodeComponent("_9"),
    container47: makeNodeComponent("container47"),
    container48: makeNodeComponent("container48"),
    container49: makeNodeComponent("container49"),
    container50: makeNodeComponent("container50"),
    container45: makeNodeComponent("container45"),
    container44: makeNodeComponent("container44"),
    customerSatisfactionRating: makeNodeComponent("customerSatisfactionRating"),
    container43: makeNodeComponent("container43"),
    image6: makeNodeComponent("image6"),
    container76: makeNodeComponent("container76"),
    image20: makeNodeComponent("image20"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    tag23: makeNodeComponent("tag23"),
    frame: makeNodeComponent("frame"),
    tag22: makeNodeComponent("tag22"),
    frame2: makeNodeComponent("frame2"),
    tag21: makeNodeComponent("tag21"),
    frame3: makeNodeComponent("frame3"),
    newMarketingReportKip: makeNodeComponent("newMarketingReportKip"),
    newOperationReportKip: makeNodeComponent("newOperationReportKip"),
    newCustomerServiceKpiReportTotal: makeNodeComponent(
      "newCustomerServiceKpiReportTotal"
    ),
    reportNewOperationReport: makeNodeComponent("reportNewOperationReport"),
    sumOfCrewMembers: makeNodeComponent("sumOfCrewMembers"),
    checkbox12: makeNodeComponent("checkbox12"),
    frame4: makeNodeComponent("frame4"),
    rectangle: makeNodeComponent("rectangle"),
    image5: makeNodeComponent("image5"),
    image8: makeNodeComponent("image8"),
    image12: makeNodeComponent("image12"),
    container100: makeNodeComponent("container100"),
    rectangle63: makeNodeComponent("rectangle63"),
    container101: makeNodeComponent("container101"),
    rectangle64: makeNodeComponent("rectangle64"),
    container102: makeNodeComponent("container102"),
    rectangle65: makeNodeComponent("rectangle65"),
    container82: makeNodeComponent("container82"),
    container77: makeNodeComponent("container77"),
    container75: makeNodeComponent("container75"),
    container78: makeNodeComponent("container78"),
    container80: makeNodeComponent("container80"),
    newFinanceReportKip: makeNodeComponent("newFinanceReportKip"),
    viewReportNewFinanceReport: makeNodeComponent("viewReportNewFinanceReport"),
    yuliyasStarship: makeNodeComponent("yuliyasStarship"),
    someStarship: makeNodeComponent("someStarship"),
    image9: makeNodeComponent("image9"),
    image13: makeNodeComponent("image13"),
    image11: makeNodeComponent("image11"),
    someStarship2: makeNodeComponent("someStarship2"),
    container81: makeNodeComponent("container81"),
    image7: makeNodeComponent("image7"),
    image17: makeNodeComponent("image17"),
    container84: makeNodeComponent("container84"),
    image10: makeNodeComponent("image10"),
    newSalesKpiReportTotal2: makeNodeComponent("newSalesKpiReportTotal2"),
    container85: makeNodeComponent("container85"),
    headerMenu1: makeNodeComponent("headerMenu1"),
    frame5: makeNodeComponent("frame5"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    image14: makeNodeComponent("image14"),

    // Metadata about props expected for PlasmicKpireports
    internalVariantProps: PlasmicKpireports__VariantProps,
    internalArgProps: PlasmicKpireports__ArgProps
  }
);

export default PlasmicKpireports;
/* prettier-ignore-end */
