// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bVumzfkpaXXcvNmP8r5aNd
// Component: ZtX7ZBalZ-ss

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bVumzfkpaXXcvNmP8r5aNd/projectcss
import sty from "./PlasmicCustomeranalytics.module.css"; // plasmic-import: ZtX7ZBalZ-ss/css

import MoveUpIcon from "./icons/PlasmicIcon__MoveUp"; // plasmic-import: 4dzxyHkIUjrn/icon
import EAddIcon from "./icons/PlasmicIcon__EAdd"; // plasmic-import: po1Da24WvXgn/icon
import QuestionMark1Icon from "./icons/PlasmicIcon__QuestionMark1"; // plasmic-import: yY_Xh4fGKtqL/icon
import Bell1Icon from "./icons/PlasmicIcon__Bell1"; // plasmic-import: n9zUMqSDbSlh/icon
import ChevronLeftLarge2Icon from "./icons/PlasmicIcon__ChevronLeftLarge2"; // plasmic-import: 30zyGFeQWZh_/icon
import Menu6Icon from "./icons/PlasmicIcon__Menu6"; // plasmic-import: lfzhQMhY_L3d/icon
import ChevronRightLarge2Icon from "./icons/PlasmicIcon__ChevronRightLarge2"; // plasmic-import: JVVd5LzXaNie/icon
import Layout11Icon from "./icons/PlasmicIcon__Layout11"; // plasmic-import: zToZXXJTB9dc/icon
import FolderIcon from "./icons/PlasmicIcon__Folder"; // plasmic-import: 90X0AxWg__s9/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: hCmqTbEa_XEh/icon
import FarmerMarketIcon from "./icons/PlasmicIcon__FarmerMarket"; // plasmic-import: 5cySklPsBu5b/icon
import CalendarIcon from "./icons/PlasmicIcon__Calendar"; // plasmic-import: c4V_2BCP5vb8/icon
import FChatIcon from "./icons/PlasmicIcon__FChat"; // plasmic-import: 6b5_xU8yWQFY/icon
import CandlestickChartIcon from "./icons/PlasmicIcon__CandlestickChart"; // plasmic-import: ZYZreGho0u9b/icon
import WhiskersIcon from "./icons/PlasmicIcon__Whiskers"; // plasmic-import: 6QYFPKXZ9GqK/icon

createPlasmicElementProxy;

export type PlasmicCustomeranalytics__VariantMembers = {};
export type PlasmicCustomeranalytics__VariantsArgs = {};
type VariantPropType = keyof PlasmicCustomeranalytics__VariantsArgs;
export const PlasmicCustomeranalytics__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCustomeranalytics__ArgsType = {};
type ArgPropType = keyof PlasmicCustomeranalytics__ArgsType;
export const PlasmicCustomeranalytics__ArgProps = new Array<ArgPropType>();

export type PlasmicCustomeranalytics__OverridesType = {
  root?: Flex__<"div">;
  wireframe9?: Flex__<"div">;
  dataTable?: Flex__<"div">;
  button15?: Flex__<"div">;
  container39?: Flex__<"div">;
  avatar3?: Flex__<"div">;
  rectangle?: Flex__<"div">;
  button16?: Flex__<"div">;
  container41?: Flex__<"div">;
  button18?: Flex__<"div">;
  text?: Flex__<"div">;
  button19?: Flex__<"div">;
  button20?: Flex__<"div">;
  button21?: Flex__<"div">;
  button22?: Flex__<"div">;
  text2?: Flex__<"div">;
  button23?: Flex__<"div">;
  button24?: Flex__<"div">;
  button25?: Flex__<"div">;
  text3?: Flex__<"div">;
  button26?: Flex__<"div">;
  container42?: Flex__<"div">;
  sidebarMenu1?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  sidebarMenu3?: Flex__<"div">;
  frame3?: Flex__<"div">;
  frame4?: Flex__<"div">;
  frame5?: Flex__<"div">;
  customerInsights?: Flex__<"div">;
  frame6?: Flex__<"div">;
  frame7?: Flex__<"div">;
  image?: Flex__<"div">;
  table2?: Flex__<"div">;
  row?: Flex__<"div">;
  frame8?: Flex__<"div">;
  frame9?: Flex__<"div">;
  frame10?: Flex__<"div">;
  frame11?: Flex__<"div">;
  frame12?: Flex__<"div">;
  tag?: Flex__<"div">;
  frame13?: Flex__<"div">;
  row2?: Flex__<"div">;
  frame14?: Flex__<"div">;
  upsellPrmiumProducts?: Flex__<"div">;
  frame15?: Flex__<"div">;
  frame16?: Flex__<"div">;
  frame17?: Flex__<"div">;
  frame18?: Flex__<"div">;
  tag2?: Flex__<"div">;
  frame19?: Flex__<"div">;
  row3?: Flex__<"div">;
  frame20?: Flex__<"div">;
  frame21?: Flex__<"div">;
  frame22?: Flex__<"div">;
  frame23?: Flex__<"div">;
  frame24?: Flex__<"div">;
  tag3?: Flex__<"div">;
  frame25?: Flex__<"div">;
  row4?: Flex__<"div">;
  frame26?: Flex__<"div">;
  frame27?: Flex__<"div">;
  frame28?: Flex__<"div">;
  tag4?: Flex__<"div">;
  frame29?: Flex__<"div">;
  frame30?: Flex__<"div">;
  frame31?: Flex__<"div">;
  header?: Flex__<"div">;
  frame32?: Flex__<"div">;
  frame33?: Flex__<"div">;
  frame34?: Flex__<"div">;
  frame35?: Flex__<"div">;
  frame36?: Flex__<"div">;
  customerAnalytics?: Flex__<"div">;
};

export interface DefaultCustomeranalyticsProps {
  className?: string;
}

const $$ = {};

function PlasmicCustomeranalytics__RenderFunc(props: {
  variants: PlasmicCustomeranalytics__VariantsArgs;
  args: PlasmicCustomeranalytics__ArgsType;
  overrides: PlasmicCustomeranalytics__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"wireframe9"}
        data-plasmic-override={overrides.wireframe9}
        className={classNames(projectcss.all, sty.wireframe9)}
      >
        <div
          data-plasmic-name={"dataTable"}
          data-plasmic-override={overrides.dataTable}
          className={classNames(projectcss.all, sty.dataTable)}
        >
          <div
            data-plasmic-name={"button15"}
            data-plasmic-override={overrides.button15}
            className={classNames(projectcss.all, sty.button15)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hdmwd
              )}
            >
              {"Export"}
            </div>
            <MoveUpIcon
              className={classNames(projectcss.all, sty.svg__bzobn)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"container39"}
            data-plasmic-override={overrides.container39}
            className={classNames(projectcss.all, sty.container39)}
          >
            <div
              data-plasmic-name={"avatar3"}
              data-plasmic-override={overrides.avatar3}
              className={classNames(projectcss.all, sty.avatar3)}
            >
              <div
                data-plasmic-name={"rectangle"}
                data-plasmic-override={overrides.rectangle}
                className={classNames(projectcss.all, sty.rectangle)}
              />
            </div>
            <div
              data-plasmic-name={"button16"}
              data-plasmic-override={overrides.button16}
              className={classNames(projectcss.all, sty.button16)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8FBzI
                )}
              >
                {"Add report"}
              </div>
              <EAddIcon
                className={classNames(projectcss.all, sty.svg__qtOl2)}
                role={"img"}
              />
            </div>
            <QuestionMark1Icon
              className={classNames(projectcss.all, sty.svg__o3UX0)}
              role={"img"}
            />

            <Bell1Icon
              className={classNames(projectcss.all, sty.svg__lly0H)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__w8E0G
              )}
            >
              {"Customer Insights and Segmentation"}
            </div>
          </div>
          <div
            data-plasmic-name={"container41"}
            data-plasmic-override={overrides.container41}
            className={classNames(projectcss.all, sty.container41)}
          >
            <div
              data-plasmic-name={"button18"}
              data-plasmic-override={overrides.button18}
              className={classNames(projectcss.all, sty.button18)}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {""}
              </div>
              <ChevronLeftLarge2Icon
                className={classNames(projectcss.all, sty.svg__nx6AU)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"button19"}
              data-plasmic-override={overrides.button19}
              className={classNames(projectcss.all, sty.button19)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___83Igb
                )}
              >
                {"2"}
              </div>
            </div>
            <div
              data-plasmic-name={"button20"}
              data-plasmic-override={overrides.button20}
              className={classNames(projectcss.all, sty.button20)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pspn6
                )}
              >
                {"3"}
              </div>
            </div>
            <div
              data-plasmic-name={"button21"}
              data-plasmic-override={overrides.button21}
              className={classNames(projectcss.all, sty.button21)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tc14V
                )}
              >
                {"4"}
              </div>
            </div>
            <div
              data-plasmic-name={"button22"}
              data-plasmic-override={overrides.button22}
              className={classNames(projectcss.all, sty.button22)}
            >
              <div
                data-plasmic-name={"text2"}
                data-plasmic-override={overrides.text2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text2
                )}
              >
                {""}
              </div>
              <Menu6Icon
                className={classNames(projectcss.all, sty.svg__n6Jdd)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"button23"}
              data-plasmic-override={overrides.button23}
              className={classNames(projectcss.all, sty.button23)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__z6Uqc
                )}
              >
                {"10"}
              </div>
            </div>
            <div
              data-plasmic-name={"button24"}
              data-plasmic-override={overrides.button24}
              className={classNames(projectcss.all, sty.button24)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ptXfa
                )}
              >
                {"11"}
              </div>
            </div>
            <div
              data-plasmic-name={"button25"}
              data-plasmic-override={overrides.button25}
              className={classNames(projectcss.all, sty.button25)}
            >
              <div
                data-plasmic-name={"text3"}
                data-plasmic-override={overrides.text3}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text3
                )}
              >
                {""}
              </div>
              <ChevronRightLarge2Icon
                className={classNames(projectcss.all, sty.svg__l5Sg)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"button26"}
              data-plasmic-override={overrides.button26}
              className={classNames(projectcss.all, sty.button26)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tfv4
                )}
              >
                {"1"}
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__icx6E
              )}
            >
              {"106 results"}
            </div>
          </div>
          <div
            data-plasmic-name={"container42"}
            data-plasmic-override={overrides.container42}
            className={classNames(projectcss.all, sty.container42)}
          >
            <div
              data-plasmic-name={"sidebarMenu1"}
              data-plasmic-override={overrides.sidebarMenu1}
              className={classNames(projectcss.all, sty.sidebarMenu1)}
            >
              <div
                data-plasmic-name={"frame"}
                data-plasmic-override={overrides.frame}
                className={classNames(projectcss.all, sty.frame)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zJxtn
                  )}
                >
                  {"Dashboard"}
                </div>
                <Layout11Icon
                  className={classNames(projectcss.all, sty.svg__kiHcn)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"frame2"}
                data-plasmic-override={overrides.frame2}
                className={classNames(projectcss.all, sty.frame2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Xevg
                  )}
                >
                  {"Data Integration and Aggregation"}
                </div>
                <FolderIcon
                  className={classNames(projectcss.all, sty.svg__aJrwh)}
                  role={"img"}
                />
              </div>
            </div>
            <Line1Icon
              className={classNames(projectcss.all, sty.svg__dJDd)}
              role={"img"}
            />

            <Line1Icon
              className={classNames(projectcss.all, sty.svg__wAyOt)}
              role={"img"}
            />

            <div
              data-plasmic-name={"sidebarMenu3"}
              data-plasmic-override={overrides.sidebarMenu3}
              className={classNames(projectcss.all, sty.sidebarMenu3)}
            >
              <div
                data-plasmic-name={"frame3"}
                data-plasmic-override={overrides.frame3}
                className={classNames(projectcss.all, sty.frame3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bl1Wj
                  )}
                >
                  {"Market and Competitive"}
                </div>
                <FarmerMarketIcon
                  className={classNames(projectcss.all, sty.svg__hAv8R)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"frame4"}
                data-plasmic-override={overrides.frame4}
                className={classNames(projectcss.all, sty.frame4)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zBk4H
                  )}
                >
                  {"Business Process Analysis:"}
                </div>
                <CalendarIcon
                  className={classNames(projectcss.all, sty.svg__h3Ynu)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"frame5"}
                data-plasmic-override={overrides.frame5}
                className={classNames(projectcss.all, sty.frame5)}
              >
                <div
                  data-plasmic-name={"customerInsights"}
                  data-plasmic-override={overrides.customerInsights}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.customerInsights
                  )}
                >
                  {"Customer Insights "}
                </div>
                <FChatIcon
                  className={classNames(projectcss.all, sty.svg__jXmUc)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"frame6"}
                data-plasmic-override={overrides.frame6}
                className={classNames(projectcss.all, sty.frame6)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jFcdI
                  )}
                >
                  {"Financial Performance"}
                </div>
                <CandlestickChartIcon
                  className={classNames(projectcss.all, sty.svg__wNNb)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                className={classNames(projectcss.all, sty.frame7)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iFynq
                  )}
                >
                  {"Risk Identification"}
                </div>
                <WhiskersIcon
                  className={classNames(projectcss.all, sty.svg__fTkLa)}
                  role={"img"}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"image"}
              data-plasmic-override={overrides.image}
              className={classNames(projectcss.all, sty.image)}
            />
          </div>
          <div
            data-plasmic-name={"table2"}
            data-plasmic-override={overrides.table2}
            className={classNames(projectcss.all, sty.table2)}
          >
            <div
              data-plasmic-name={"row"}
              data-plasmic-override={overrides.row}
              className={classNames(projectcss.all, sty.row)}
            >
              <div
                data-plasmic-name={"frame8"}
                data-plasmic-override={overrides.frame8}
                className={classNames(projectcss.all, sty.frame8)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9YQrJ
                  )}
                >
                  {"20 purchases, $1,200 total\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame9"}
                data-plasmic-override={overrides.frame9}
                className={classNames(projectcss.all, sty.frame9)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dNlmk
                  )}
                >
                  {"20 purchases, $1,200 total\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame10"}
                data-plasmic-override={overrides.frame10}
                className={classNames(projectcss.all, sty.frame10)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7Zu7E
                  )}
                >
                  {"001"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame11"}
                data-plasmic-override={overrides.frame11}
                className={classNames(projectcss.all, sty.frame11)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cin0Y
                  )}
                >
                  {"Age: 30, Male, Rubavu"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame12"}
                data-plasmic-override={overrides.frame12}
                className={classNames(projectcss.all, sty.frame12)}
              >
                <div
                  data-plasmic-name={"tag"}
                  data-plasmic-override={overrides.tag}
                  className={classNames(projectcss.all, sty.tag)}
                >
                  <div
                    data-plasmic-name={"frame13"}
                    data-plasmic-override={overrides.frame13}
                    className={classNames(projectcss.all, sty.frame13)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gEyw4
                      )}
                    >
                      {"95%"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"row2"}
              data-plasmic-override={overrides.row2}
              className={classNames(projectcss.all, sty.row2)}
            >
              <div
                data-plasmic-name={"frame14"}
                data-plasmic-override={overrides.frame14}
                className={classNames(projectcss.all, sty.frame14)}
              >
                <div
                  data-plasmic-name={"upsellPrmiumProducts"}
                  data-plasmic-override={overrides.upsellPrmiumProducts}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.upsellPrmiumProducts
                  )}
                >
                  {"Upsell prmium products\n"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame15"}
                data-plasmic-override={overrides.frame15}
                className={classNames(projectcss.all, sty.frame15)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i6XMk
                  )}
                >
                  {"Age: 45, Female, Kicukiro"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame16"}
                data-plasmic-override={overrides.frame16}
                className={classNames(projectcss.all, sty.frame16)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eXwNu
                  )}
                >
                  {"002"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame17"}
                data-plasmic-override={overrides.frame17}
                className={classNames(projectcss.all, sty.frame17)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fjRep
                  )}
                >
                  {"35 purchases, $2,300 total\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame18"}
                data-plasmic-override={overrides.frame18}
                className={classNames(projectcss.all, sty.frame18)}
              >
                <div
                  data-plasmic-name={"tag2"}
                  data-plasmic-override={overrides.tag2}
                  className={classNames(projectcss.all, sty.tag2)}
                >
                  <div
                    data-plasmic-name={"frame19"}
                    data-plasmic-override={overrides.frame19}
                    className={classNames(projectcss.all, sty.frame19)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jIdUg
                      )}
                    >
                      {"33%"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"row3"}
              data-plasmic-override={overrides.row3}
              className={classNames(projectcss.all, sty.row3)}
            >
              <div
                data-plasmic-name={"frame20"}
                data-plasmic-override={overrides.frame20}
                className={classNames(projectcss.all, sty.frame20)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b3VzW
                  )}
                >
                  {"Personalized marketing"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame21"}
                data-plasmic-override={overrides.frame21}
                className={classNames(projectcss.all, sty.frame21)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qWhVw
                  )}
                >
                  {"Age: 29, Female, Musanze"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame22"}
                data-plasmic-override={overrides.frame22}
                className={classNames(projectcss.all, sty.frame22)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ddA8U
                  )}
                >
                  {"003"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame23"}
                data-plasmic-override={overrides.frame23}
                className={classNames(projectcss.all, sty.frame23)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jb0Zf
                  )}
                >
                  {"10 purchases, $500 total\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame24"}
                data-plasmic-override={overrides.frame24}
                className={classNames(projectcss.all, sty.frame24)}
              >
                <div
                  data-plasmic-name={"tag3"}
                  data-plasmic-override={overrides.tag3}
                  className={classNames(projectcss.all, sty.tag3)}
                >
                  <div
                    data-plasmic-name={"frame25"}
                    data-plasmic-override={overrides.frame25}
                    className={classNames(projectcss.all, sty.frame25)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5FUeA
                      )}
                    >
                      {"69%"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"row4"}
              data-plasmic-override={overrides.row4}
              className={classNames(projectcss.all, sty.row4)}
            >
              <div
                data-plasmic-name={"frame26"}
                data-plasmic-override={overrides.frame26}
                className={classNames(projectcss.all, sty.frame26)}
              />

              <div
                data-plasmic-name={"frame27"}
                data-plasmic-override={overrides.frame27}
                className={classNames(projectcss.all, sty.frame27)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__feAtF
                  )}
                >
                  {"003"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame28"}
                data-plasmic-override={overrides.frame28}
                className={classNames(projectcss.all, sty.frame28)}
              >
                <div
                  data-plasmic-name={"tag4"}
                  data-plasmic-override={overrides.tag4}
                  className={classNames(projectcss.all, sty.tag4)}
                >
                  <div
                    data-plasmic-name={"frame29"}
                    data-plasmic-override={overrides.frame29}
                    className={classNames(projectcss.all, sty.frame29)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__v51Kc
                      )}
                    >
                      {"26%"}
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"frame30"}
                data-plasmic-override={overrides.frame30}
                className={classNames(projectcss.all, sty.frame30)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d8Bay
                  )}
                >
                  {"2,034"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame31"}
                data-plasmic-override={overrides.frame31}
                className={classNames(projectcss.all, sty.frame31)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lOf0G
                  )}
                >
                  {"1,000"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"frame32"}
                data-plasmic-override={overrides.frame32}
                className={classNames(projectcss.all, sty.frame32)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bnjBf
                  )}
                >
                  {"Recommended Actions"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame33"}
                data-plasmic-override={overrides.frame33}
                className={classNames(projectcss.all, sty.frame33)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Sqp1
                  )}
                >
                  {"Churn Risk (%)\t\n"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame34"}
                data-plasmic-override={overrides.frame34}
                className={classNames(projectcss.all, sty.frame34)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hbGst
                  )}
                >
                  {"Demographics\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame35"}
                data-plasmic-override={overrides.frame35}
                className={classNames(projectcss.all, sty.frame35)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bajNk
                  )}
                >
                  {"Customer ID\t"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame36"}
                data-plasmic-override={overrides.frame36}
                className={classNames(projectcss.all, sty.frame36)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8L2P
                  )}
                >
                  {"Purchase History\t"}
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"customerAnalytics"}
            data-plasmic-override={overrides.customerAnalytics}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.customerAnalytics
            )}
          >
            {" Customer Analytics"}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "wireframe9",
    "dataTable",
    "button15",
    "container39",
    "avatar3",
    "rectangle",
    "button16",
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26",
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "table2",
    "row",
    "frame8",
    "frame9",
    "frame10",
    "frame11",
    "frame12",
    "tag",
    "frame13",
    "row2",
    "frame14",
    "upsellPrmiumProducts",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "tag2",
    "frame19",
    "row3",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "tag3",
    "frame25",
    "row4",
    "frame26",
    "frame27",
    "frame28",
    "tag4",
    "frame29",
    "frame30",
    "frame31",
    "header",
    "frame32",
    "frame33",
    "frame34",
    "frame35",
    "frame36",
    "customerAnalytics"
  ],
  wireframe9: [
    "wireframe9",
    "dataTable",
    "button15",
    "container39",
    "avatar3",
    "rectangle",
    "button16",
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26",
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "table2",
    "row",
    "frame8",
    "frame9",
    "frame10",
    "frame11",
    "frame12",
    "tag",
    "frame13",
    "row2",
    "frame14",
    "upsellPrmiumProducts",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "tag2",
    "frame19",
    "row3",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "tag3",
    "frame25",
    "row4",
    "frame26",
    "frame27",
    "frame28",
    "tag4",
    "frame29",
    "frame30",
    "frame31",
    "header",
    "frame32",
    "frame33",
    "frame34",
    "frame35",
    "frame36",
    "customerAnalytics"
  ],
  dataTable: [
    "dataTable",
    "button15",
    "container39",
    "avatar3",
    "rectangle",
    "button16",
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26",
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "table2",
    "row",
    "frame8",
    "frame9",
    "frame10",
    "frame11",
    "frame12",
    "tag",
    "frame13",
    "row2",
    "frame14",
    "upsellPrmiumProducts",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "tag2",
    "frame19",
    "row3",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "tag3",
    "frame25",
    "row4",
    "frame26",
    "frame27",
    "frame28",
    "tag4",
    "frame29",
    "frame30",
    "frame31",
    "header",
    "frame32",
    "frame33",
    "frame34",
    "frame35",
    "frame36",
    "customerAnalytics"
  ],
  button15: ["button15"],
  container39: ["container39", "avatar3", "rectangle", "button16"],
  avatar3: ["avatar3", "rectangle"],
  rectangle: ["rectangle"],
  button16: ["button16"],
  container41: [
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26"
  ],
  button18: ["button18", "text"],
  text: ["text"],
  button19: ["button19"],
  button20: ["button20"],
  button21: ["button21"],
  button22: ["button22", "text2"],
  text2: ["text2"],
  button23: ["button23"],
  button24: ["button24"],
  button25: ["button25", "text3"],
  text3: ["text3"],
  button26: ["button26"],
  container42: [
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image"
  ],
  sidebarMenu1: ["sidebarMenu1", "frame", "frame2"],
  frame: ["frame"],
  frame2: ["frame2"],
  sidebarMenu3: [
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7"
  ],
  frame3: ["frame3"],
  frame4: ["frame4"],
  frame5: ["frame5", "customerInsights"],
  customerInsights: ["customerInsights"],
  frame6: ["frame6"],
  frame7: ["frame7"],
  image: ["image"],
  table2: [
    "table2",
    "row",
    "frame8",
    "frame9",
    "frame10",
    "frame11",
    "frame12",
    "tag",
    "frame13",
    "row2",
    "frame14",
    "upsellPrmiumProducts",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "tag2",
    "frame19",
    "row3",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "tag3",
    "frame25",
    "row4",
    "frame26",
    "frame27",
    "frame28",
    "tag4",
    "frame29",
    "frame30",
    "frame31",
    "header",
    "frame32",
    "frame33",
    "frame34",
    "frame35",
    "frame36"
  ],
  row: [
    "row",
    "frame8",
    "frame9",
    "frame10",
    "frame11",
    "frame12",
    "tag",
    "frame13"
  ],
  frame8: ["frame8"],
  frame9: ["frame9"],
  frame10: ["frame10"],
  frame11: ["frame11"],
  frame12: ["frame12", "tag", "frame13"],
  tag: ["tag", "frame13"],
  frame13: ["frame13"],
  row2: [
    "row2",
    "frame14",
    "upsellPrmiumProducts",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "tag2",
    "frame19"
  ],
  frame14: ["frame14", "upsellPrmiumProducts"],
  upsellPrmiumProducts: ["upsellPrmiumProducts"],
  frame15: ["frame15"],
  frame16: ["frame16"],
  frame17: ["frame17"],
  frame18: ["frame18", "tag2", "frame19"],
  tag2: ["tag2", "frame19"],
  frame19: ["frame19"],
  row3: [
    "row3",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "tag3",
    "frame25"
  ],
  frame20: ["frame20"],
  frame21: ["frame21"],
  frame22: ["frame22"],
  frame23: ["frame23"],
  frame24: ["frame24", "tag3", "frame25"],
  tag3: ["tag3", "frame25"],
  frame25: ["frame25"],
  row4: [
    "row4",
    "frame26",
    "frame27",
    "frame28",
    "tag4",
    "frame29",
    "frame30",
    "frame31"
  ],
  frame26: ["frame26"],
  frame27: ["frame27"],
  frame28: ["frame28", "tag4", "frame29"],
  tag4: ["tag4", "frame29"],
  frame29: ["frame29"],
  frame30: ["frame30"],
  frame31: ["frame31"],
  header: ["header", "frame32", "frame33", "frame34", "frame35", "frame36"],
  frame32: ["frame32"],
  frame33: ["frame33"],
  frame34: ["frame34"],
  frame35: ["frame35"],
  frame36: ["frame36"],
  customerAnalytics: ["customerAnalytics"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  wireframe9: "div";
  dataTable: "div";
  button15: "div";
  container39: "div";
  avatar3: "div";
  rectangle: "div";
  button16: "div";
  container41: "div";
  button18: "div";
  text: "div";
  button19: "div";
  button20: "div";
  button21: "div";
  button22: "div";
  text2: "div";
  button23: "div";
  button24: "div";
  button25: "div";
  text3: "div";
  button26: "div";
  container42: "div";
  sidebarMenu1: "div";
  frame: "div";
  frame2: "div";
  sidebarMenu3: "div";
  frame3: "div";
  frame4: "div";
  frame5: "div";
  customerInsights: "div";
  frame6: "div";
  frame7: "div";
  image: "div";
  table2: "div";
  row: "div";
  frame8: "div";
  frame9: "div";
  frame10: "div";
  frame11: "div";
  frame12: "div";
  tag: "div";
  frame13: "div";
  row2: "div";
  frame14: "div";
  upsellPrmiumProducts: "div";
  frame15: "div";
  frame16: "div";
  frame17: "div";
  frame18: "div";
  tag2: "div";
  frame19: "div";
  row3: "div";
  frame20: "div";
  frame21: "div";
  frame22: "div";
  frame23: "div";
  frame24: "div";
  tag3: "div";
  frame25: "div";
  row4: "div";
  frame26: "div";
  frame27: "div";
  frame28: "div";
  tag4: "div";
  frame29: "div";
  frame30: "div";
  frame31: "div";
  header: "div";
  frame32: "div";
  frame33: "div";
  frame34: "div";
  frame35: "div";
  frame36: "div";
  customerAnalytics: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCustomeranalytics__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCustomeranalytics__VariantsArgs;
    args?: PlasmicCustomeranalytics__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCustomeranalytics__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCustomeranalytics__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomeranalytics__ArgProps,
          internalVariantPropNames: PlasmicCustomeranalytics__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomeranalytics__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCustomeranalytics";
  } else {
    func.displayName = `PlasmicCustomeranalytics.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomeranalytics = Object.assign(
  // Top-level PlasmicCustomeranalytics renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wireframe9: makeNodeComponent("wireframe9"),
    dataTable: makeNodeComponent("dataTable"),
    button15: makeNodeComponent("button15"),
    container39: makeNodeComponent("container39"),
    avatar3: makeNodeComponent("avatar3"),
    rectangle: makeNodeComponent("rectangle"),
    button16: makeNodeComponent("button16"),
    container41: makeNodeComponent("container41"),
    button18: makeNodeComponent("button18"),
    text: makeNodeComponent("text"),
    button19: makeNodeComponent("button19"),
    button20: makeNodeComponent("button20"),
    button21: makeNodeComponent("button21"),
    button22: makeNodeComponent("button22"),
    text2: makeNodeComponent("text2"),
    button23: makeNodeComponent("button23"),
    button24: makeNodeComponent("button24"),
    button25: makeNodeComponent("button25"),
    text3: makeNodeComponent("text3"),
    button26: makeNodeComponent("button26"),
    container42: makeNodeComponent("container42"),
    sidebarMenu1: makeNodeComponent("sidebarMenu1"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    sidebarMenu3: makeNodeComponent("sidebarMenu3"),
    frame3: makeNodeComponent("frame3"),
    frame4: makeNodeComponent("frame4"),
    frame5: makeNodeComponent("frame5"),
    customerInsights: makeNodeComponent("customerInsights"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    image: makeNodeComponent("image"),
    table2: makeNodeComponent("table2"),
    row: makeNodeComponent("row"),
    frame8: makeNodeComponent("frame8"),
    frame9: makeNodeComponent("frame9"),
    frame10: makeNodeComponent("frame10"),
    frame11: makeNodeComponent("frame11"),
    frame12: makeNodeComponent("frame12"),
    tag: makeNodeComponent("tag"),
    frame13: makeNodeComponent("frame13"),
    row2: makeNodeComponent("row2"),
    frame14: makeNodeComponent("frame14"),
    upsellPrmiumProducts: makeNodeComponent("upsellPrmiumProducts"),
    frame15: makeNodeComponent("frame15"),
    frame16: makeNodeComponent("frame16"),
    frame17: makeNodeComponent("frame17"),
    frame18: makeNodeComponent("frame18"),
    tag2: makeNodeComponent("tag2"),
    frame19: makeNodeComponent("frame19"),
    row3: makeNodeComponent("row3"),
    frame20: makeNodeComponent("frame20"),
    frame21: makeNodeComponent("frame21"),
    frame22: makeNodeComponent("frame22"),
    frame23: makeNodeComponent("frame23"),
    frame24: makeNodeComponent("frame24"),
    tag3: makeNodeComponent("tag3"),
    frame25: makeNodeComponent("frame25"),
    row4: makeNodeComponent("row4"),
    frame26: makeNodeComponent("frame26"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    tag4: makeNodeComponent("tag4"),
    frame29: makeNodeComponent("frame29"),
    frame30: makeNodeComponent("frame30"),
    frame31: makeNodeComponent("frame31"),
    header: makeNodeComponent("header"),
    frame32: makeNodeComponent("frame32"),
    frame33: makeNodeComponent("frame33"),
    frame34: makeNodeComponent("frame34"),
    frame35: makeNodeComponent("frame35"),
    frame36: makeNodeComponent("frame36"),
    customerAnalytics: makeNodeComponent("customerAnalytics"),

    // Metadata about props expected for PlasmicCustomeranalytics
    internalVariantProps: PlasmicCustomeranalytics__VariantProps,
    internalArgProps: PlasmicCustomeranalytics__ArgProps
  }
);

export default PlasmicCustomeranalytics;
/* prettier-ignore-end */
