// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bVumzfkpaXXcvNmP8r5aNd
// Component: qjjd9G4j-a7z

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bVumzfkpaXXcvNmP8r5aNd/projectcss
import sty from "./PlasmicFinancialperformancea.module.css"; // plasmic-import: qjjd9G4j-a7z/css

import Bell1Icon from "./icons/PlasmicIcon__Bell1"; // plasmic-import: n9zUMqSDbSlh/icon
import FChatIcon from "./icons/PlasmicIcon__FChat"; // plasmic-import: 6b5_xU8yWQFY/icon
import Help1Icon from "./icons/PlasmicIcon__Help1"; // plasmic-import: 0RZKNW_B9hOX/icon
import ChevronRightLargeIcon from "./icons/PlasmicIcon__ChevronRightLarge"; // plasmic-import: VaHzNZUH3H4M/icon
import EllipseIcon from "./icons/PlasmicIcon__Ellipse"; // plasmic-import: OL9uoJ4OqaKE/icon
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: 7sVE2sTKpTbi/icon
import Line19Icon from "./icons/PlasmicIcon__Line19"; // plasmic-import: yPnb2-47kSa1/icon
import Frame11Icon from "./icons/PlasmicIcon__Frame11"; // plasmic-import: iW6gDtSCOsOa/icon
import Line24Icon from "./icons/PlasmicIcon__Line24"; // plasmic-import: kI0letG9xEg1/icon
import Frame12Icon from "./icons/PlasmicIcon__Frame12"; // plasmic-import: HjzhfjuGX-1j/icon
import Line25Icon from "./icons/PlasmicIcon__Line25"; // plasmic-import: OR2emMtfEHvS/icon
import Line30Icon from "./icons/PlasmicIcon__Line30"; // plasmic-import: dF5gA1IINKoe/icon
import ChevronDownLargeIcon from "./icons/PlasmicIcon__ChevronDownLarge"; // plasmic-import: MF4N_3wKmh_O/icon
import chart41YQyVw9WVTuB from "./images/chart4.svg"; // plasmic-import: 1yQyVw9wVTuB/picture
import chart5A8Mp5RmyPCw5 from "./images/chart5.svg"; // plasmic-import: a8Mp5rmyPCw5/picture
import chart6Xe2Q0DmSe6Gy from "./images/chart6.svg"; // plasmic-import: Xe2Q0DMSe6gy/picture
import oval1UdkkVqHcPkN8 from "./images/oval1.svg"; // plasmic-import: udkkVQHcPkN8/picture
import switch1F9NGlvk6RmTc from "./images/switch1.svg"; // plasmic-import: F9NGlvk6RmTc/picture
import oval2JoRcrAyEv4Xb from "./images/oval2.svg"; // plasmic-import: joRCRAyEv4xb/picture

createPlasmicElementProxy;

export type PlasmicFinancialperformancea__VariantMembers = {};
export type PlasmicFinancialperformancea__VariantsArgs = {};
type VariantPropType = keyof PlasmicFinancialperformancea__VariantsArgs;
export const PlasmicFinancialperformancea__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFinancialperformancea__ArgsType = {};
type ArgPropType = keyof PlasmicFinancialperformancea__ArgsType;
export const PlasmicFinancialperformancea__ArgProps = new Array<ArgPropType>();

export type PlasmicFinancialperformancea__OverridesType = {
  root?: Flex__<"div">;
  wireframe10?: Flex__<"div">;
  financialDashboard2?: Flex__<"div">;
  container127?: Flex__<"div">;
  avatar16?: Flex__<"div">;
  rectangle?: Flex__<"div">;
  container128?: Flex__<"div">;
  button124?: Flex__<"div">;
  container129?: Flex__<"div">;
  button125?: Flex__<"div">;
  container130?: Flex__<"div">;
  button126?: Flex__<"div">;
  container131?: Flex__<"div">;
  pieChart4?: Flex__<"div">;
  pieChart5?: Flex__<"div">;
  container132?: Flex__<"div">;
  pieChart6?: Flex__<"div">;
  frame?: Flex__<"div">;
  group?: Flex__<"div">;
  group2?: Flex__<"div">;
  group3?: Flex__<"div">;
  tag16?: Flex__<"div">;
  frame2?: Flex__<"div">;
  tag17?: Flex__<"div">;
  frame3?: Flex__<"div">;
  tag18?: Flex__<"div">;
  frame4?: Flex__<"div">;
  container133?: Flex__<"div">;
  lineChart6?: Flex__<"div">;
  frame5?: Flex__<"div">;
  lineChart7?: Flex__<"div">;
  frame6?: Flex__<"div">;
  container134?: Flex__<"div">;
  rectangle16?: Flex__<"div">;
  rectangle17?: Flex__<"div">;
  container135?: Flex__<"div">;
  rectangle18?: Flex__<"div">;
  rectangle19?: Flex__<"div">;
  rectangle20?: Flex__<"div">;
  rectangle21?: Flex__<"div">;
  rectangle22?: Flex__<"div">;
  rectangle23?: Flex__<"div">;
  rectangle24?: Flex__<"div">;
  rectangle25?: Flex__<"div">;
  rectangle26?: Flex__<"div">;
  rectangle27?: Flex__<"div">;
  rectangle28?: Flex__<"div">;
  dropdownButton5?: Flex__<"div">;
  image?: Flex__<"div">;
};

export interface DefaultFinancialperformanceaProps {
  className?: string;
}

const $$ = {};

function PlasmicFinancialperformancea__RenderFunc(props: {
  variants: PlasmicFinancialperformancea__VariantsArgs;
  args: PlasmicFinancialperformancea__ArgsType;
  overrides: PlasmicFinancialperformancea__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"wireframe10"}
            data-plasmic-override={overrides.wireframe10}
            className={classNames(projectcss.all, sty.wireframe10)}
          >
            <div
              data-plasmic-name={"financialDashboard2"}
              data-plasmic-override={overrides.financialDashboard2}
              className={classNames(projectcss.all, sty.financialDashboard2)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pw7Mj
                )}
              >
                {"Financial Dashboard"}
              </div>
              <div
                data-plasmic-name={"container127"}
                data-plasmic-override={overrides.container127}
                className={classNames(projectcss.all, sty.container127)}
              >
                <Bell1Icon
                  className={classNames(projectcss.all, sty.svg__kQo5)}
                  role={"img"}
                />

                <FChatIcon
                  className={classNames(projectcss.all, sty.svg__lhZgQ)}
                  role={"img"}
                />

                <Help1Icon
                  className={classNames(projectcss.all, sty.svg__eiS8H)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"avatar16"}
                  data-plasmic-override={overrides.avatar16}
                  className={classNames(projectcss.all, sty.avatar16)}
                >
                  <div
                    data-plasmic-name={"rectangle"}
                    data-plasmic-override={overrides.rectangle}
                    className={classNames(projectcss.all, sty.rectangle)}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pBzE
                  )}
                >
                  {" Financial Performance Analysis"}
                </div>
              </div>
              <div
                data-plasmic-name={"container128"}
                data-plasmic-override={overrides.container128}
                className={classNames(projectcss.all, sty.container128)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t76Vm
                  )}
                >
                  {"Total Assets"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rumCp
                  )}
                >
                  {"250,000"}
                </div>
                <div
                  data-plasmic-name={"button124"}
                  data-plasmic-override={overrides.button124}
                  className={classNames(projectcss.all, sty.button124)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rLWsX
                    )}
                  >
                    {"Detail"}
                  </div>
                  <ChevronRightLargeIcon
                    className={classNames(projectcss.all, sty.svg__s8Mm5)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"container129"}
                data-plasmic-override={overrides.container129}
                className={classNames(projectcss.all, sty.container129)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Qhj
                  )}
                >
                  {"Total Liabilities"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ekmMu
                  )}
                >
                  {"50,000"}
                </div>
                <div
                  data-plasmic-name={"button125"}
                  data-plasmic-override={overrides.button125}
                  className={classNames(projectcss.all, sty.button125)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rgpnn
                    )}
                  >
                    {"Detail"}
                  </div>
                  <ChevronRightLargeIcon
                    className={classNames(projectcss.all, sty.svg__mHfmr)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"container130"}
                data-plasmic-override={overrides.container130}
                className={classNames(projectcss.all, sty.container130)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wPlpK
                  )}
                >
                  {"Net Worth"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5Rg0I
                  )}
                >
                  {"$200,000"}
                </div>
                <div
                  data-plasmic-name={"button126"}
                  data-plasmic-override={overrides.button126}
                  className={classNames(projectcss.all, sty.button126)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cHsFj
                    )}
                  >
                    {"Detail"}
                  </div>
                  <ChevronRightLargeIcon
                    className={classNames(projectcss.all, sty.svg__bljT)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"container131"}
                data-plasmic-override={overrides.container131}
                className={classNames(projectcss.all, sty.container131)}
              >
                <div
                  data-plasmic-name={"pieChart4"}
                  data-plasmic-override={overrides.pieChart4}
                  className={classNames(projectcss.all, sty.pieChart4)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bDoQ)}
                    displayHeight={"218px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"218px"}
                    loading={"lazy"}
                    src={{
                      src: chart41YQyVw9WVTuB,
                      fullWidth: 218,
                      fullHeight: 218,
                      aspectRatio: 1
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"pieChart5"}
                  data-plasmic-override={overrides.pieChart5}
                  className={classNames(projectcss.all, sty.pieChart5)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kDbwf)}
                    displayHeight={"218px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"218px"}
                    loading={"lazy"}
                    src={{
                      src: chart5A8Mp5RmyPCw5,
                      fullWidth: 218,
                      fullHeight: 218,
                      aspectRatio: 1
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lhQ8O
                  )}
                >
                  {"Profit Margin"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8L3L
                  )}
                >
                  {"Gross Profit Margin"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s67Zw
                  )}
                >
                  {"Net Profit Margin"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hsSLg
                  )}
                >
                  {"40%"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h3Zer
                  )}
                >
                  {"20%"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eY4F
                  )}
                >
                  {"$60,000"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fZc6O
                  )}
                >
                  {"$25,000"}
                </div>
              </div>
              <div
                data-plasmic-name={"container132"}
                data-plasmic-override={overrides.container132}
                className={classNames(projectcss.all, sty.container132)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k9OKq
                  )}
                >
                  {"liquidity"}
                </div>
                <div
                  data-plasmic-name={"pieChart6"}
                  data-plasmic-override={overrides.pieChart6}
                  className={classNames(projectcss.all, sty.pieChart6)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__vwSH)}
                    displayHeight={"255px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"255px"}
                    loading={"lazy"}
                    src={{
                      src: chart6Xe2Q0DmSe6Gy,
                      fullWidth: 255,
                      fullHeight: 255,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    className={classNames(projectcss.all, sty.frame)}
                  >
                    <div
                      data-plasmic-name={"group"}
                      data-plasmic-override={overrides.group}
                      className={classNames(projectcss.all, sty.group)}
                    >
                      <EllipseIcon
                        className={classNames(projectcss.all, sty.svg__sgKlo)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ipbE
                        )}
                      >
                        {"Paid"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"group2"}
                      data-plasmic-override={overrides.group2}
                      className={classNames(projectcss.all, sty.group2)}
                    >
                      <EllipseIcon
                        className={classNames(projectcss.all, sty.svg__svZiR)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hHx3
                        )}
                      >
                        {"Pending"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"group3"}
                      data-plasmic-override={overrides.group3}
                      className={classNames(projectcss.all, sty.group3)}
                    >
                      <Ellipse2Icon
                        className={classNames(projectcss.all, sty.svg__psQoi)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4L6D2
                        )}
                      >
                        {"Failed"}
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"tag16"}
                  data-plasmic-override={overrides.tag16}
                  className={classNames(projectcss.all, sty.tag16)}
                >
                  <div
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    className={classNames(projectcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wpnw7
                      )}
                    >
                      {"10%"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"tag17"}
                  data-plasmic-override={overrides.tag17}
                  className={classNames(projectcss.all, sty.tag17)}
                >
                  <div
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ivMrc
                      )}
                    >
                      {"50%"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"tag18"}
                  data-plasmic-override={overrides.tag18}
                  className={classNames(projectcss.all, sty.tag18)}
                >
                  <div
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5Wzif
                      )}
                    >
                      {"40%"}
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container133"}
                data-plasmic-override={overrides.container133}
                className={classNames(projectcss.all, sty.container133)}
              >
                <Line19Icon
                  className={classNames(projectcss.all, sty.svg___5EnR)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__biu7V
                  )}
                >
                  {"balance sheets"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0VbFa
                  )}
                >
                  {"0"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8PacD
                  )}
                >
                  {"August"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__idYfI
                  )}
                >
                  {"December"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q2VHo
                  )}
                >
                  {"September"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Iq4V
                  )}
                >
                  {"November"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__r4Mea
                  )}
                >
                  {"October"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yl3Vm
                  )}
                >
                  {"$100k"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c1LUg
                  )}
                >
                  {"July"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sIixs
                  )}
                >
                  {"$75k"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vv6LN
                  )}
                >
                  {"$50k"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u2D71
                  )}
                >
                  {"$25k"}
                </div>
                <Line19Icon
                  className={classNames(projectcss.all, sty.svg__iIlOq)}
                  role={"img"}
                />

                <Line19Icon
                  className={classNames(projectcss.all, sty.svg__o2QwP)}
                  role={"img"}
                />

                <Line19Icon
                  className={classNames(projectcss.all, sty.svg__fF7NH)}
                  role={"img"}
                />

                <Line19Icon
                  className={classNames(projectcss.all, sty.svg___7MiDz)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"lineChart6"}
                  data-plasmic-override={overrides.lineChart6}
                  className={classNames(projectcss.all, sty.lineChart6)}
                >
                  <div
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <Frame11Icon
                      className={classNames(projectcss.all, sty.svg__us42I)}
                      role={"img"}
                    />
                  </div>
                </div>
                <Line24Icon
                  className={classNames(projectcss.all, sty.svg__qFflg)}
                  role={"img"}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jUaO8)}
                  displayHeight={"20px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"20px"}
                  loading={"lazy"}
                  src={{
                    src: oval1UdkkVqHcPkN8,
                    fullWidth: 20,
                    fullHeight: 20,
                    aspectRatio: 1
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__j4Ife)}
                  displayHeight={"20px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  loading={"lazy"}
                  src={{
                    src: switch1F9NGlvk6RmTc,
                    fullWidth: 32,
                    fullHeight: 20,
                    aspectRatio: 1.6
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hiOqo
                  )}
                >
                  {"Compare previous period"}
                </div>
                <div
                  data-plasmic-name={"lineChart7"}
                  data-plasmic-override={overrides.lineChart7}
                  className={classNames(projectcss.all, sty.lineChart7)}
                >
                  <div
                    data-plasmic-name={"frame6"}
                    data-plasmic-override={overrides.frame6}
                    className={classNames(projectcss.all, sty.frame6)}
                  >
                    <Frame12Icon
                      className={classNames(projectcss.all, sty.svg__d9ES)}
                      role={"img"}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"container134"}
                  data-plasmic-override={overrides.container134}
                  className={classNames(projectcss.all, sty.container134)}
                >
                  <div
                    data-plasmic-name={"rectangle16"}
                    data-plasmic-override={overrides.rectangle16}
                    className={classNames(projectcss.all, sty.rectangle16)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d8RgZ
                    )}
                  >
                    {"This year"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zVefF
                    )}
                  >
                    {"85,000"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qzoIo
                    )}
                  >
                    {"October"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d4Jaj
                    )}
                  >
                    {"Last year "}
                  </div>
                  <div
                    data-plasmic-name={"rectangle17"}
                    data-plasmic-override={overrides.rectangle17}
                    className={classNames(projectcss.all, sty.rectangle17)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zMz4O
                    )}
                  >
                    {"35,000"}
                  </div>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___5G1I)}
                  displayHeight={"20px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"20px"}
                  loading={"lazy"}
                  src={{
                    src: oval2JoRcrAyEv4Xb,
                    fullWidth: 20,
                    fullHeight: 20,
                    aspectRatio: 1
                  }}
                />
              </div>
              <div
                data-plasmic-name={"container135"}
                data-plasmic-override={overrides.container135}
                className={classNames(projectcss.all, sty.container135)}
              >
                <Line25Icon
                  className={classNames(projectcss.all, sty.svg___0Wnhy)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gmj6C
                  )}
                >
                  {"Cash Flow"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hdyrf
                  )}
                >
                  {"0"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fWkA5
                  )}
                >
                  {"Rent and Utilities"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9OGHx
                  )}
                >
                  {"Investing Activities"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Oug2
                  )}
                >
                  {"Inventory Purchases"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__quEwh
                  )}
                >
                  {"Purchase of New Equipment"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iAltg
                  )}
                >
                  {"$100k"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l50S
                  )}
                >
                  {"Sales"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rosH8
                  )}
                >
                  {"$75k"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8UVlh
                  )}
                >
                  {"$50k"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y2Fpu
                  )}
                >
                  {"$25k"}
                </div>
                <Line25Icon
                  className={classNames(projectcss.all, sty.svg__hGp85)}
                  role={"img"}
                />

                <Line25Icon
                  className={classNames(projectcss.all, sty.svg__ebHiW)}
                  role={"img"}
                />

                <Line25Icon
                  className={classNames(projectcss.all, sty.svg__h78F)}
                  role={"img"}
                />

                <Line25Icon
                  className={classNames(projectcss.all, sty.svg__ig1Sz)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"rectangle18"}
                  data-plasmic-override={overrides.rectangle18}
                  className={classNames(projectcss.all, sty.rectangle18)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___53Qf
                  )}
                >
                  {"Cash inflow"}
                </div>
                <div
                  data-plasmic-name={"rectangle19"}
                  data-plasmic-override={overrides.rectangle19}
                  className={classNames(projectcss.all, sty.rectangle19)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eAp8D
                  )}
                >
                  {"Cash outflow"}
                </div>
                <div
                  data-plasmic-name={"rectangle20"}
                  data-plasmic-override={overrides.rectangle20}
                  className={classNames(projectcss.all, sty.rectangle20)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x4UzT
                  )}
                >
                  {"Sale of Equipment"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Y3Zg
                  )}
                >
                  {"Bank Loan"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qcXiU
                  )}
                >
                  {"Repayment of Loan"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jvZwl
                  )}
                >
                  {"Total"}
                </div>
                <div
                  data-plasmic-name={"rectangle21"}
                  data-plasmic-override={overrides.rectangle21}
                  className={classNames(projectcss.all, sty.rectangle21)}
                />

                <div
                  data-plasmic-name={"rectangle22"}
                  data-plasmic-override={overrides.rectangle22}
                  className={classNames(projectcss.all, sty.rectangle22)}
                />

                <div
                  data-plasmic-name={"rectangle23"}
                  data-plasmic-override={overrides.rectangle23}
                  className={classNames(projectcss.all, sty.rectangle23)}
                />

                <div
                  data-plasmic-name={"rectangle24"}
                  data-plasmic-override={overrides.rectangle24}
                  className={classNames(projectcss.all, sty.rectangle24)}
                />

                <div
                  data-plasmic-name={"rectangle25"}
                  data-plasmic-override={overrides.rectangle25}
                  className={classNames(projectcss.all, sty.rectangle25)}
                />

                <div
                  data-plasmic-name={"rectangle26"}
                  data-plasmic-override={overrides.rectangle26}
                  className={classNames(projectcss.all, sty.rectangle26)}
                />

                <div
                  data-plasmic-name={"rectangle27"}
                  data-plasmic-override={overrides.rectangle27}
                  className={classNames(projectcss.all, sty.rectangle27)}
                />

                <div
                  data-plasmic-name={"rectangle28"}
                  data-plasmic-override={overrides.rectangle28}
                  className={classNames(projectcss.all, sty.rectangle28)}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg___417E)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__kVq9)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__frwWf)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__uJcvM)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__pWuR1)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__bScUl)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__d5Jmg)}
                  role={"img"}
                />

                <Line30Icon
                  className={classNames(projectcss.all, sty.svg__gorbJ)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"dropdownButton5"}
                  data-plasmic-override={overrides.dropdownButton5}
                  className={classNames(projectcss.all, sty.dropdownButton5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wpg6G
                    )}
                  >
                    {"December"}
                  </div>
                  <ChevronDownLargeIcon
                    className={classNames(projectcss.all, sty.svg__rFhkS)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"image"}
                data-plasmic-override={overrides.image}
                className={classNames(projectcss.all, sty.image)}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "wireframe10",
    "financialDashboard2",
    "container127",
    "avatar16",
    "rectangle",
    "container128",
    "button124",
    "container129",
    "button125",
    "container130",
    "button126",
    "container131",
    "pieChart4",
    "pieChart5",
    "container132",
    "pieChart6",
    "frame",
    "group",
    "group2",
    "group3",
    "tag16",
    "frame2",
    "tag17",
    "frame3",
    "tag18",
    "frame4",
    "container133",
    "lineChart6",
    "frame5",
    "lineChart7",
    "frame6",
    "container134",
    "rectangle16",
    "rectangle17",
    "container135",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "dropdownButton5",
    "image"
  ],
  wireframe10: [
    "wireframe10",
    "financialDashboard2",
    "container127",
    "avatar16",
    "rectangle",
    "container128",
    "button124",
    "container129",
    "button125",
    "container130",
    "button126",
    "container131",
    "pieChart4",
    "pieChart5",
    "container132",
    "pieChart6",
    "frame",
    "group",
    "group2",
    "group3",
    "tag16",
    "frame2",
    "tag17",
    "frame3",
    "tag18",
    "frame4",
    "container133",
    "lineChart6",
    "frame5",
    "lineChart7",
    "frame6",
    "container134",
    "rectangle16",
    "rectangle17",
    "container135",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "dropdownButton5",
    "image"
  ],
  financialDashboard2: [
    "financialDashboard2",
    "container127",
    "avatar16",
    "rectangle",
    "container128",
    "button124",
    "container129",
    "button125",
    "container130",
    "button126",
    "container131",
    "pieChart4",
    "pieChart5",
    "container132",
    "pieChart6",
    "frame",
    "group",
    "group2",
    "group3",
    "tag16",
    "frame2",
    "tag17",
    "frame3",
    "tag18",
    "frame4",
    "container133",
    "lineChart6",
    "frame5",
    "lineChart7",
    "frame6",
    "container134",
    "rectangle16",
    "rectangle17",
    "container135",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "dropdownButton5",
    "image"
  ],
  container127: ["container127", "avatar16", "rectangle"],
  avatar16: ["avatar16", "rectangle"],
  rectangle: ["rectangle"],
  container128: ["container128", "button124"],
  button124: ["button124"],
  container129: ["container129", "button125"],
  button125: ["button125"],
  container130: ["container130", "button126"],
  button126: ["button126"],
  container131: ["container131", "pieChart4", "pieChart5"],
  pieChart4: ["pieChart4"],
  pieChart5: ["pieChart5"],
  container132: [
    "container132",
    "pieChart6",
    "frame",
    "group",
    "group2",
    "group3",
    "tag16",
    "frame2",
    "tag17",
    "frame3",
    "tag18",
    "frame4"
  ],
  pieChart6: ["pieChart6", "frame", "group", "group2", "group3"],
  frame: ["frame", "group", "group2", "group3"],
  group: ["group"],
  group2: ["group2"],
  group3: ["group3"],
  tag16: ["tag16", "frame2"],
  frame2: ["frame2"],
  tag17: ["tag17", "frame3"],
  frame3: ["frame3"],
  tag18: ["tag18", "frame4"],
  frame4: ["frame4"],
  container133: [
    "container133",
    "lineChart6",
    "frame5",
    "lineChart7",
    "frame6",
    "container134",
    "rectangle16",
    "rectangle17"
  ],
  lineChart6: ["lineChart6", "frame5"],
  frame5: ["frame5"],
  lineChart7: ["lineChart7", "frame6"],
  frame6: ["frame6"],
  container134: ["container134", "rectangle16", "rectangle17"],
  rectangle16: ["rectangle16"],
  rectangle17: ["rectangle17"],
  container135: [
    "container135",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle23",
    "rectangle24",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "dropdownButton5"
  ],
  rectangle18: ["rectangle18"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  rectangle22: ["rectangle22"],
  rectangle23: ["rectangle23"],
  rectangle24: ["rectangle24"],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"],
  dropdownButton5: ["dropdownButton5"],
  image: ["image"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  wireframe10: "div";
  financialDashboard2: "div";
  container127: "div";
  avatar16: "div";
  rectangle: "div";
  container128: "div";
  button124: "div";
  container129: "div";
  button125: "div";
  container130: "div";
  button126: "div";
  container131: "div";
  pieChart4: "div";
  pieChart5: "div";
  container132: "div";
  pieChart6: "div";
  frame: "div";
  group: "div";
  group2: "div";
  group3: "div";
  tag16: "div";
  frame2: "div";
  tag17: "div";
  frame3: "div";
  tag18: "div";
  frame4: "div";
  container133: "div";
  lineChart6: "div";
  frame5: "div";
  lineChart7: "div";
  frame6: "div";
  container134: "div";
  rectangle16: "div";
  rectangle17: "div";
  container135: "div";
  rectangle18: "div";
  rectangle19: "div";
  rectangle20: "div";
  rectangle21: "div";
  rectangle22: "div";
  rectangle23: "div";
  rectangle24: "div";
  rectangle25: "div";
  rectangle26: "div";
  rectangle27: "div";
  rectangle28: "div";
  dropdownButton5: "div";
  image: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFinancialperformancea__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFinancialperformancea__VariantsArgs;
    args?: PlasmicFinancialperformancea__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFinancialperformancea__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFinancialperformancea__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFinancialperformancea__ArgProps,
          internalVariantPropNames: PlasmicFinancialperformancea__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFinancialperformancea__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFinancialperformancea";
  } else {
    func.displayName = `PlasmicFinancialperformancea.${nodeName}`;
  }
  return func;
}

export const PlasmicFinancialperformancea = Object.assign(
  // Top-level PlasmicFinancialperformancea renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wireframe10: makeNodeComponent("wireframe10"),
    financialDashboard2: makeNodeComponent("financialDashboard2"),
    container127: makeNodeComponent("container127"),
    avatar16: makeNodeComponent("avatar16"),
    rectangle: makeNodeComponent("rectangle"),
    container128: makeNodeComponent("container128"),
    button124: makeNodeComponent("button124"),
    container129: makeNodeComponent("container129"),
    button125: makeNodeComponent("button125"),
    container130: makeNodeComponent("container130"),
    button126: makeNodeComponent("button126"),
    container131: makeNodeComponent("container131"),
    pieChart4: makeNodeComponent("pieChart4"),
    pieChart5: makeNodeComponent("pieChart5"),
    container132: makeNodeComponent("container132"),
    pieChart6: makeNodeComponent("pieChart6"),
    frame: makeNodeComponent("frame"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    tag16: makeNodeComponent("tag16"),
    frame2: makeNodeComponent("frame2"),
    tag17: makeNodeComponent("tag17"),
    frame3: makeNodeComponent("frame3"),
    tag18: makeNodeComponent("tag18"),
    frame4: makeNodeComponent("frame4"),
    container133: makeNodeComponent("container133"),
    lineChart6: makeNodeComponent("lineChart6"),
    frame5: makeNodeComponent("frame5"),
    lineChart7: makeNodeComponent("lineChart7"),
    frame6: makeNodeComponent("frame6"),
    container134: makeNodeComponent("container134"),
    rectangle16: makeNodeComponent("rectangle16"),
    rectangle17: makeNodeComponent("rectangle17"),
    container135: makeNodeComponent("container135"),
    rectangle18: makeNodeComponent("rectangle18"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    rectangle22: makeNodeComponent("rectangle22"),
    rectangle23: makeNodeComponent("rectangle23"),
    rectangle24: makeNodeComponent("rectangle24"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    dropdownButton5: makeNodeComponent("dropdownButton5"),
    image: makeNodeComponent("image"),

    // Metadata about props expected for PlasmicFinancialperformancea
    internalVariantProps: PlasmicFinancialperformancea__VariantProps,
    internalArgProps: PlasmicFinancialperformancea__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFinancialperformancea;
/* prettier-ignore-end */
