// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bVumzfkpaXXcvNmP8r5aNd
// Component: dz-IFOlVs6PO

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bVumzfkpaXXcvNmP8r5aNd/projectcss
import sty from "./PlasmicFinancialperformance.module.css"; // plasmic-import: dz-IFOlVs6PO/css

import DownloadIcon from "./icons/PlasmicIcon__Download"; // plasmic-import: 0-AgzpxQF9ix/icon
import MoveUpIcon from "./icons/PlasmicIcon__MoveUp"; // plasmic-import: 4dzxyHkIUjrn/icon
import EAddIcon from "./icons/PlasmicIcon__EAdd"; // plasmic-import: po1Da24WvXgn/icon
import QuestionMark1Icon from "./icons/PlasmicIcon__QuestionMark1"; // plasmic-import: yY_Xh4fGKtqL/icon
import Bell1Icon from "./icons/PlasmicIcon__Bell1"; // plasmic-import: n9zUMqSDbSlh/icon
import ChevronLeftLarge2Icon from "./icons/PlasmicIcon__ChevronLeftLarge2"; // plasmic-import: 30zyGFeQWZh_/icon
import Menu6Icon from "./icons/PlasmicIcon__Menu6"; // plasmic-import: lfzhQMhY_L3d/icon
import ChevronRightLarge2Icon from "./icons/PlasmicIcon__ChevronRightLarge2"; // plasmic-import: JVVd5LzXaNie/icon
import Layout11Icon from "./icons/PlasmicIcon__Layout11"; // plasmic-import: zToZXXJTB9dc/icon
import FolderIcon from "./icons/PlasmicIcon__Folder"; // plasmic-import: 90X0AxWg__s9/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: hCmqTbEa_XEh/icon
import FarmerMarketIcon from "./icons/PlasmicIcon__FarmerMarket"; // plasmic-import: 5cySklPsBu5b/icon
import CalendarIcon from "./icons/PlasmicIcon__Calendar"; // plasmic-import: c4V_2BCP5vb8/icon
import FChatIcon from "./icons/PlasmicIcon__FChat"; // plasmic-import: 6b5_xU8yWQFY/icon
import CandlestickChartIcon from "./icons/PlasmicIcon__CandlestickChart"; // plasmic-import: ZYZreGho0u9b/icon
import WhiskersIcon from "./icons/PlasmicIcon__Whiskers"; // plasmic-import: 6QYFPKXZ9GqK/icon
import ERemove2Icon from "./icons/PlasmicIcon__ERemove2"; // plasmic-import: TG8NH336Lsj7/icon
import Frame3Icon from "./icons/PlasmicIcon__Frame3"; // plasmic-import: _8JbPW7aiK1X/icon
import Frame4Icon from "./icons/PlasmicIcon__Frame4"; // plasmic-import: nBUziPG46gYl/icon
import chart2Tc19Ht3B2BNw from "./images/chart2.svg"; // plasmic-import: TC19ht3B2bNW/picture
import chart3Wlg2H3GkQgc from "./images/chart3.svg"; // plasmic-import: Wlg2h3Gk_Qgc/picture

createPlasmicElementProxy;

export type PlasmicFinancialperformance__VariantMembers = {};
export type PlasmicFinancialperformance__VariantsArgs = {};
type VariantPropType = keyof PlasmicFinancialperformance__VariantsArgs;
export const PlasmicFinancialperformance__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFinancialperformance__ArgsType = {};
type ArgPropType = keyof PlasmicFinancialperformance__ArgsType;
export const PlasmicFinancialperformance__ArgProps = new Array<ArgPropType>();

export type PlasmicFinancialperformance__OverridesType = {
  root?: Flex__<"div">;
  wireframe5?: Flex__<"div">;
  dataTable?: Flex__<"div">;
  button14?: Flex__<"div">;
  button15?: Flex__<"div">;
  container39?: Flex__<"div">;
  avatar3?: Flex__<"div">;
  rectangle?: Flex__<"div">;
  button16?: Flex__<"div">;
  container41?: Flex__<"div">;
  button18?: Flex__<"div">;
  text?: Flex__<"div">;
  button19?: Flex__<"div">;
  button20?: Flex__<"div">;
  button21?: Flex__<"div">;
  button22?: Flex__<"div">;
  text2?: Flex__<"div">;
  button23?: Flex__<"div">;
  button24?: Flex__<"div">;
  button25?: Flex__<"div">;
  text3?: Flex__<"div">;
  button26?: Flex__<"div">;
  container42?: Flex__<"div">;
  sidebarMenu1?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  sidebarMenu3?: Flex__<"div">;
  frame3?: Flex__<"div">;
  frame4?: Flex__<"div">;
  frame5?: Flex__<"div">;
  customerInsights?: Flex__<"div">;
  frame6?: Flex__<"div">;
  frame7?: Flex__<"div">;
  image?: Flex__<"div">;
  container138?: Flex__<"div">;
  selectTemplate?: Flex__<"div">;
  container139?: Flex__<"div">;
  container140?: Flex__<"div">;
  container141?: Flex__<"div">;
  lineChart6?: Flex__<"div">;
  frame8?: Flex__<"div">;
  rectangle66?: Flex__<"div">;
  rectangle67?: Flex__<"div">;
  rectangle68?: Flex__<"div">;
  rectangle69?: Flex__<"div">;
  userAnalysis?: Flex__<"div">;
  button55?: Flex__<"div">;
  viewDemo?: Flex__<"div">;
  container142?: Flex__<"div">;
  container143?: Flex__<"div">;
  container144?: Flex__<"div">;
  columnBarChart5?: Flex__<"div">;
  chart?: Flex__<"div">;
  rectangle2?: Flex__<"div">;
  rectangle3?: Flex__<"div">;
  rectangle4?: Flex__<"div">;
  rectangle5?: Flex__<"div">;
  rectangle6?: Flex__<"div">;
  rectangle7?: Flex__<"div">;
  rectangle8?: Flex__<"div">;
  rectangle9?: Flex__<"div">;
  rectangle10?: Flex__<"div">;
  rectangle11?: Flex__<"div">;
  rectangle70?: Flex__<"div">;
  rectangle71?: Flex__<"div">;
  rectangle72?: Flex__<"div">;
  rectangle73?: Flex__<"div">;
  marketingsKpi?: Flex__<"div">;
  button57?: Flex__<"div">;
  viewDemo2?: Flex__<"div">;
  container145?: Flex__<"div">;
  container146?: Flex__<"div">;
  container147?: Flex__<"div">;
  insightfulInteractions?: Flex__<"div">;
  rectangle74?: Flex__<"div">;
  rectangle75?: Flex__<"div">;
  rectangle76?: Flex__<"div">;
  rectangle77?: Flex__<"div">;
  pieChart5?: Flex__<"div">;
  pieChart6?: Flex__<"div">;
  insightfulInteractions2?: Flex__<"div">;
  button59?: Flex__<"div">;
  viewDemo3?: Flex__<"div">;
  button60?: Flex__<"div">;
};

export interface DefaultFinancialperformanceProps {
  className?: string;
}

const $$ = {};

function PlasmicFinancialperformance__RenderFunc(props: {
  variants: PlasmicFinancialperformance__VariantsArgs;
  args: PlasmicFinancialperformance__ArgsType;
  overrides: PlasmicFinancialperformance__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"wireframe5"}
            data-plasmic-override={overrides.wireframe5}
            className={classNames(projectcss.all, sty.wireframe5)}
          >
            <div
              data-plasmic-name={"dataTable"}
              data-plasmic-override={overrides.dataTable}
              className={classNames(projectcss.all, sty.dataTable)}
            >
              <div
                data-plasmic-name={"button14"}
                data-plasmic-override={overrides.button14}
                className={classNames(projectcss.all, sty.button14)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hh02D
                  )}
                >
                  {"Import"}
                </div>
                <DownloadIcon
                  className={classNames(projectcss.all, sty.svg__aAloy)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"button15"}
                data-plasmic-override={overrides.button15}
                className={classNames(projectcss.all, sty.button15)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w42Ie
                  )}
                >
                  {"Export"}
                </div>
                <MoveUpIcon
                  className={classNames(projectcss.all, sty.svg__i8Zp2)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"container39"}
                data-plasmic-override={overrides.container39}
                className={classNames(projectcss.all, sty.container39)}
              >
                <div
                  data-plasmic-name={"avatar3"}
                  data-plasmic-override={overrides.avatar3}
                  className={classNames(projectcss.all, sty.avatar3)}
                >
                  <div
                    data-plasmic-name={"rectangle"}
                    data-plasmic-override={overrides.rectangle}
                    className={classNames(projectcss.all, sty.rectangle)}
                  />
                </div>
                <div
                  data-plasmic-name={"button16"}
                  data-plasmic-override={overrides.button16}
                  className={classNames(projectcss.all, sty.button16)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vTiH
                    )}
                  >
                    {"Add report"}
                  </div>
                  <EAddIcon
                    className={classNames(projectcss.all, sty.svg__iJ8L)}
                    role={"img"}
                  />
                </div>
                <QuestionMark1Icon
                  className={classNames(projectcss.all, sty.svg__m82Vx)}
                  role={"img"}
                />

                <Bell1Icon
                  className={classNames(projectcss.all, sty.svg__zftrG)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hoLys
                  )}
                >
                  {" Performance Dashboards and KPI Monitoring"}
                </div>
              </div>
              <div
                data-plasmic-name={"container41"}
                data-plasmic-override={overrides.container41}
                className={classNames(projectcss.all, sty.container41)}
              >
                <div
                  data-plasmic-name={"button18"}
                  data-plasmic-override={overrides.button18}
                  className={classNames(projectcss.all, sty.button18)}
                >
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {""}
                  </div>
                  <ChevronLeftLarge2Icon
                    className={classNames(projectcss.all, sty.svg___8PzkI)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"button19"}
                  data-plasmic-override={overrides.button19}
                  className={classNames(projectcss.all, sty.button19)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zdJbg
                    )}
                  >
                    {"2"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"button20"}
                  data-plasmic-override={overrides.button20}
                  className={classNames(projectcss.all, sty.button20)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rg8X2
                    )}
                  >
                    {"3"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"button21"}
                  data-plasmic-override={overrides.button21}
                  className={classNames(projectcss.all, sty.button21)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qvanE
                    )}
                  >
                    {"4"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"button22"}
                  data-plasmic-override={overrides.button22}
                  className={classNames(projectcss.all, sty.button22)}
                >
                  <div
                    data-plasmic-name={"text2"}
                    data-plasmic-override={overrides.text2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text2
                    )}
                  >
                    {""}
                  </div>
                  <Menu6Icon
                    className={classNames(projectcss.all, sty.svg__gsHYc)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"button23"}
                  data-plasmic-override={overrides.button23}
                  className={classNames(projectcss.all, sty.button23)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f3S9B
                    )}
                  >
                    {"10"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"button24"}
                  data-plasmic-override={overrides.button24}
                  className={classNames(projectcss.all, sty.button24)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xZoxi
                    )}
                  >
                    {"11"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"button25"}
                  data-plasmic-override={overrides.button25}
                  className={classNames(projectcss.all, sty.button25)}
                >
                  <div
                    data-plasmic-name={"text3"}
                    data-plasmic-override={overrides.text3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text3
                    )}
                  >
                    {""}
                  </div>
                  <ChevronRightLarge2Icon
                    className={classNames(projectcss.all, sty.svg__kaTiQ)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"button26"}
                  data-plasmic-override={overrides.button26}
                  className={classNames(projectcss.all, sty.button26)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dQ4QS
                    )}
                  >
                    {"1"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lkbCo
                  )}
                >
                  {"106 results"}
                </div>
              </div>
              <div
                data-plasmic-name={"container42"}
                data-plasmic-override={overrides.container42}
                className={classNames(projectcss.all, sty.container42)}
              >
                <div
                  data-plasmic-name={"sidebarMenu1"}
                  data-plasmic-override={overrides.sidebarMenu1}
                  className={classNames(projectcss.all, sty.sidebarMenu1)}
                >
                  <div
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    className={classNames(projectcss.all, sty.frame)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aBwC
                      )}
                    >
                      {"Dashboard"}
                    </div>
                    <Layout11Icon
                      className={classNames(projectcss.all, sty.svg__r8N1I)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    className={classNames(projectcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pO75R
                      )}
                    >
                      {"Data Integration and Aggregation"}
                    </div>
                    <FolderIcon
                      className={classNames(projectcss.all, sty.svg__h0Dvg)}
                      role={"img"}
                    />
                  </div>
                </div>
                <Line1Icon
                  className={classNames(projectcss.all, sty.svg__i2Tpn)}
                  role={"img"}
                />

                <Line1Icon
                  className={classNames(projectcss.all, sty.svg__t4Shv)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"sidebarMenu3"}
                  data-plasmic-override={overrides.sidebarMenu3}
                  className={classNames(projectcss.all, sty.sidebarMenu3)}
                >
                  <div
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3V39M
                      )}
                    >
                      {"Market and Competitive"}
                    </div>
                    <FarmerMarketIcon
                      className={classNames(projectcss.all, sty.svg__tBVo)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__br8LE
                      )}
                    >
                      {"Business Process Analysis:"}
                    </div>
                    <CalendarIcon
                      className={classNames(projectcss.all, sty.svg__kyjyn)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <div
                      data-plasmic-name={"customerInsights"}
                      data-plasmic-override={overrides.customerInsights}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.customerInsights
                      )}
                    >
                      {"Customer Insights "}
                    </div>
                    <FChatIcon
                      className={classNames(projectcss.all, sty.svg__odgk)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame6"}
                    data-plasmic-override={overrides.frame6}
                    className={classNames(projectcss.all, sty.frame6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pUdSv
                      )}
                    >
                      {"Financial Performance"}
                    </div>
                    <CandlestickChartIcon
                      className={classNames(projectcss.all, sty.svg___5WGqp)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame7"}
                    data-plasmic-override={overrides.frame7}
                    className={classNames(projectcss.all, sty.frame7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eU5ZA
                      )}
                    >
                      {"Risk Identification"}
                    </div>
                    <WhiskersIcon
                      className={classNames(projectcss.all, sty.svg__fMjJn)}
                      role={"img"}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"image"}
                  data-plasmic-override={overrides.image}
                  className={classNames(projectcss.all, sty.image)}
                />
              </div>
              <div
                data-plasmic-name={"container138"}
                data-plasmic-override={overrides.container138}
                className={classNames(projectcss.all, sty.container138)}
              >
                <div
                  data-plasmic-name={"selectTemplate"}
                  data-plasmic-override={overrides.selectTemplate}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.selectTemplate
                  )}
                >
                  {"Customizable"}
                </div>
                <ERemove2Icon
                  className={classNames(projectcss.all, sty.svg__vOiw)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"container139"}
                  data-plasmic-override={overrides.container139}
                  className={classNames(projectcss.all, sty.container139)}
                >
                  <div
                    data-plasmic-name={"container140"}
                    data-plasmic-override={overrides.container140}
                    className={classNames(projectcss.all, sty.container140)}
                  >
                    <div
                      data-plasmic-name={"container141"}
                      data-plasmic-override={overrides.container141}
                      className={classNames(projectcss.all, sty.container141)}
                    >
                      <div
                        data-plasmic-name={"lineChart6"}
                        data-plasmic-override={overrides.lineChart6}
                        className={classNames(projectcss.all, sty.lineChart6)}
                      >
                        <div
                          data-plasmic-name={"frame8"}
                          data-plasmic-override={overrides.frame8}
                          className={classNames(projectcss.all, sty.frame8)}
                        >
                          <Frame3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fCyuS
                            )}
                            role={"img"}
                          />

                          <Frame4Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fhLi
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__g48Nz
                        )}
                      >
                        {"User Analysis"}
                      </div>
                      <div
                        data-plasmic-name={"rectangle66"}
                        data-plasmic-override={overrides.rectangle66}
                        className={classNames(projectcss.all, sty.rectangle66)}
                      />

                      <div
                        data-plasmic-name={"rectangle67"}
                        data-plasmic-override={overrides.rectangle67}
                        className={classNames(projectcss.all, sty.rectangle67)}
                      />

                      <div
                        data-plasmic-name={"rectangle68"}
                        data-plasmic-override={overrides.rectangle68}
                        className={classNames(projectcss.all, sty.rectangle68)}
                      />

                      <div
                        data-plasmic-name={"rectangle69"}
                        data-plasmic-override={overrides.rectangle69}
                        className={classNames(projectcss.all, sty.rectangle69)}
                      />
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"userAnalysis"}
                    data-plasmic-override={overrides.userAnalysis}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.userAnalysis
                    )}
                  >
                    {"Metrics"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pOhF1
                    )}
                  >
                    {
                      "Unlock valuable insights into user behavior and preference..."
                    }
                  </div>
                  <div
                    data-plasmic-name={"button55"}
                    data-plasmic-override={overrides.button55}
                    className={classNames(projectcss.all, sty.button55)}
                  >
                    <div
                      data-plasmic-name={"viewDemo"}
                      data-plasmic-override={overrides.viewDemo}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.viewDemo
                      )}
                    >
                      {"View more"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"container142"}
                  data-plasmic-override={overrides.container142}
                  className={classNames(projectcss.all, sty.container142)}
                >
                  <div
                    data-plasmic-name={"container143"}
                    data-plasmic-override={overrides.container143}
                    className={classNames(projectcss.all, sty.container143)}
                  >
                    <div
                      data-plasmic-name={"container144"}
                      data-plasmic-override={overrides.container144}
                      className={classNames(projectcss.all, sty.container144)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kM1Jf
                        )}
                      >
                        {"Company KPI"}
                      </div>
                      <div
                        data-plasmic-name={"columnBarChart5"}
                        data-plasmic-override={overrides.columnBarChart5}
                        className={classNames(
                          projectcss.all,
                          sty.columnBarChart5
                        )}
                      >
                        <div
                          data-plasmic-name={"chart"}
                          data-plasmic-override={overrides.chart}
                          className={classNames(projectcss.all, sty.chart)}
                        >
                          <div
                            data-plasmic-name={"rectangle2"}
                            data-plasmic-override={overrides.rectangle2}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle2
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle3"}
                            data-plasmic-override={overrides.rectangle3}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle3
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle4"}
                            data-plasmic-override={overrides.rectangle4}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle4
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle5"}
                            data-plasmic-override={overrides.rectangle5}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle5
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle6"}
                            data-plasmic-override={overrides.rectangle6}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle6
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle7"}
                            data-plasmic-override={overrides.rectangle7}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle7
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle8"}
                            data-plasmic-override={overrides.rectangle8}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle8
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle9"}
                            data-plasmic-override={overrides.rectangle9}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle9
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle10"}
                            data-plasmic-override={overrides.rectangle10}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle10
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle11"}
                            data-plasmic-override={overrides.rectangle11}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle11
                            )}
                          />
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"rectangle70"}
                        data-plasmic-override={overrides.rectangle70}
                        className={classNames(projectcss.all, sty.rectangle70)}
                      />

                      <div
                        data-plasmic-name={"rectangle71"}
                        data-plasmic-override={overrides.rectangle71}
                        className={classNames(projectcss.all, sty.rectangle71)}
                      />

                      <div
                        data-plasmic-name={"rectangle72"}
                        data-plasmic-override={overrides.rectangle72}
                        className={classNames(projectcss.all, sty.rectangle72)}
                      />

                      <div
                        data-plasmic-name={"rectangle73"}
                        data-plasmic-override={overrides.rectangle73}
                        className={classNames(projectcss.all, sty.rectangle73)}
                      />
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"marketingsKpi"}
                    data-plasmic-override={overrides.marketingsKpi}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.marketingsKpi
                    )}
                  >
                    {"Business trends across various departments"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mZTrg
                    )}
                  >
                    {
                      "Key Performance Indicators (KPIs) are specific, measurable metrics..."
                    }
                  </div>
                  <div
                    data-plasmic-name={"button57"}
                    data-plasmic-override={overrides.button57}
                    className={classNames(projectcss.all, sty.button57)}
                  >
                    <div
                      data-plasmic-name={"viewDemo2"}
                      data-plasmic-override={overrides.viewDemo2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.viewDemo2
                      )}
                    >
                      {"View more"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"container145"}
                  data-plasmic-override={overrides.container145}
                  className={classNames(projectcss.all, sty.container145)}
                >
                  <div
                    data-plasmic-name={"container146"}
                    data-plasmic-override={overrides.container146}
                    className={classNames(projectcss.all, sty.container146)}
                  >
                    <div
                      data-plasmic-name={"container147"}
                      data-plasmic-override={overrides.container147}
                      className={classNames(projectcss.all, sty.container147)}
                    >
                      <div
                        data-plasmic-name={"insightfulInteractions"}
                        data-plasmic-override={overrides.insightfulInteractions}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.insightfulInteractions
                        )}
                      >
                        {"Departmental "}
                      </div>
                      <div
                        data-plasmic-name={"rectangle74"}
                        data-plasmic-override={overrides.rectangle74}
                        className={classNames(projectcss.all, sty.rectangle74)}
                      />

                      <div
                        data-plasmic-name={"rectangle75"}
                        data-plasmic-override={overrides.rectangle75}
                        className={classNames(projectcss.all, sty.rectangle75)}
                      />

                      <div
                        data-plasmic-name={"rectangle76"}
                        data-plasmic-override={overrides.rectangle76}
                        className={classNames(projectcss.all, sty.rectangle76)}
                      />

                      <div
                        data-plasmic-name={"rectangle77"}
                        data-plasmic-override={overrides.rectangle77}
                        className={classNames(projectcss.all, sty.rectangle77)}
                      />

                      <div
                        data-plasmic-name={"pieChart5"}
                        data-plasmic-override={overrides.pieChart5}
                        className={classNames(projectcss.all, sty.pieChart5)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__r7UEu)}
                          displayHeight={"84px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"84px"}
                          loading={"lazy"}
                          src={{
                            src: chart2Tc19Ht3B2BNw,
                            fullWidth: 84,
                            fullHeight: 84,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        data-plasmic-name={"pieChart6"}
                        data-plasmic-override={overrides.pieChart6}
                        className={classNames(projectcss.all, sty.pieChart6)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__o25Gc)}
                          displayHeight={"84px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"84px"}
                          loading={"lazy"}
                          src={{
                            src: chart3Wlg2H3GkQgc,
                            fullWidth: 84,
                            fullHeight: 84,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"insightfulInteractions2"}
                    data-plasmic-override={overrides.insightfulInteractions2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.insightfulInteractions2
                    )}
                  >
                    {"Functional areas"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8F4A5
                    )}
                  >
                    {
                      "Evaluating our company's performance is a breeze with our carefully selected..."
                    }
                  </div>
                  <div
                    data-plasmic-name={"button59"}
                    data-plasmic-override={overrides.button59}
                    className={classNames(projectcss.all, sty.button59)}
                  >
                    <div
                      data-plasmic-name={"viewDemo3"}
                      data-plasmic-override={overrides.viewDemo3}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.viewDemo3
                      )}
                    >
                      {"View more"}
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ke5Wr
                    )}
                  >
                    {"KPIs"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"button60"}
                  data-plasmic-override={overrides.button60}
                  className={classNames(projectcss.all, sty.button60)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m3PjP
                    )}
                  >
                    {"Show more"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "wireframe5",
    "dataTable",
    "button14",
    "button15",
    "container39",
    "avatar3",
    "rectangle",
    "button16",
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26",
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "container138",
    "selectTemplate",
    "container139",
    "container140",
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69",
    "userAnalysis",
    "button55",
    "viewDemo",
    "container142",
    "container143",
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73",
    "marketingsKpi",
    "button57",
    "viewDemo2",
    "container145",
    "container146",
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6",
    "insightfulInteractions2",
    "button59",
    "viewDemo3",
    "button60"
  ],
  wireframe5: [
    "wireframe5",
    "dataTable",
    "button14",
    "button15",
    "container39",
    "avatar3",
    "rectangle",
    "button16",
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26",
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "container138",
    "selectTemplate",
    "container139",
    "container140",
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69",
    "userAnalysis",
    "button55",
    "viewDemo",
    "container142",
    "container143",
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73",
    "marketingsKpi",
    "button57",
    "viewDemo2",
    "container145",
    "container146",
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6",
    "insightfulInteractions2",
    "button59",
    "viewDemo3",
    "button60"
  ],
  dataTable: [
    "dataTable",
    "button14",
    "button15",
    "container39",
    "avatar3",
    "rectangle",
    "button16",
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26",
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image",
    "container138",
    "selectTemplate",
    "container139",
    "container140",
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69",
    "userAnalysis",
    "button55",
    "viewDemo",
    "container142",
    "container143",
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73",
    "marketingsKpi",
    "button57",
    "viewDemo2",
    "container145",
    "container146",
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6",
    "insightfulInteractions2",
    "button59",
    "viewDemo3",
    "button60"
  ],
  button14: ["button14"],
  button15: ["button15"],
  container39: ["container39", "avatar3", "rectangle", "button16"],
  avatar3: ["avatar3", "rectangle"],
  rectangle: ["rectangle"],
  button16: ["button16"],
  container41: [
    "container41",
    "button18",
    "text",
    "button19",
    "button20",
    "button21",
    "button22",
    "text2",
    "button23",
    "button24",
    "button25",
    "text3",
    "button26"
  ],
  button18: ["button18", "text"],
  text: ["text"],
  button19: ["button19"],
  button20: ["button20"],
  button21: ["button21"],
  button22: ["button22", "text2"],
  text2: ["text2"],
  button23: ["button23"],
  button24: ["button24"],
  button25: ["button25", "text3"],
  text3: ["text3"],
  button26: ["button26"],
  container42: [
    "container42",
    "sidebarMenu1",
    "frame",
    "frame2",
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7",
    "image"
  ],
  sidebarMenu1: ["sidebarMenu1", "frame", "frame2"],
  frame: ["frame"],
  frame2: ["frame2"],
  sidebarMenu3: [
    "sidebarMenu3",
    "frame3",
    "frame4",
    "frame5",
    "customerInsights",
    "frame6",
    "frame7"
  ],
  frame3: ["frame3"],
  frame4: ["frame4"],
  frame5: ["frame5", "customerInsights"],
  customerInsights: ["customerInsights"],
  frame6: ["frame6"],
  frame7: ["frame7"],
  image: ["image"],
  container138: [
    "container138",
    "selectTemplate",
    "container139",
    "container140",
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69",
    "userAnalysis",
    "button55",
    "viewDemo",
    "container142",
    "container143",
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73",
    "marketingsKpi",
    "button57",
    "viewDemo2",
    "container145",
    "container146",
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6",
    "insightfulInteractions2",
    "button59",
    "viewDemo3",
    "button60"
  ],
  selectTemplate: ["selectTemplate"],
  container139: [
    "container139",
    "container140",
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69",
    "userAnalysis",
    "button55",
    "viewDemo"
  ],
  container140: [
    "container140",
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69"
  ],
  container141: [
    "container141",
    "lineChart6",
    "frame8",
    "rectangle66",
    "rectangle67",
    "rectangle68",
    "rectangle69"
  ],
  lineChart6: ["lineChart6", "frame8"],
  frame8: ["frame8"],
  rectangle66: ["rectangle66"],
  rectangle67: ["rectangle67"],
  rectangle68: ["rectangle68"],
  rectangle69: ["rectangle69"],
  userAnalysis: ["userAnalysis"],
  button55: ["button55", "viewDemo"],
  viewDemo: ["viewDemo"],
  container142: [
    "container142",
    "container143",
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73",
    "marketingsKpi",
    "button57",
    "viewDemo2"
  ],
  container143: [
    "container143",
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73"
  ],
  container144: [
    "container144",
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle70",
    "rectangle71",
    "rectangle72",
    "rectangle73"
  ],
  columnBarChart5: [
    "columnBarChart5",
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11"
  ],
  chart: [
    "chart",
    "rectangle2",
    "rectangle3",
    "rectangle4",
    "rectangle5",
    "rectangle6",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11"
  ],
  rectangle2: ["rectangle2"],
  rectangle3: ["rectangle3"],
  rectangle4: ["rectangle4"],
  rectangle5: ["rectangle5"],
  rectangle6: ["rectangle6"],
  rectangle7: ["rectangle7"],
  rectangle8: ["rectangle8"],
  rectangle9: ["rectangle9"],
  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  rectangle70: ["rectangle70"],
  rectangle71: ["rectangle71"],
  rectangle72: ["rectangle72"],
  rectangle73: ["rectangle73"],
  marketingsKpi: ["marketingsKpi"],
  button57: ["button57", "viewDemo2"],
  viewDemo2: ["viewDemo2"],
  container145: [
    "container145",
    "container146",
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6",
    "insightfulInteractions2",
    "button59",
    "viewDemo3"
  ],
  container146: [
    "container146",
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6"
  ],
  container147: [
    "container147",
    "insightfulInteractions",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "rectangle77",
    "pieChart5",
    "pieChart6"
  ],
  insightfulInteractions: ["insightfulInteractions"],
  rectangle74: ["rectangle74"],
  rectangle75: ["rectangle75"],
  rectangle76: ["rectangle76"],
  rectangle77: ["rectangle77"],
  pieChart5: ["pieChart5"],
  pieChart6: ["pieChart6"],
  insightfulInteractions2: ["insightfulInteractions2"],
  button59: ["button59", "viewDemo3"],
  viewDemo3: ["viewDemo3"],
  button60: ["button60"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  wireframe5: "div";
  dataTable: "div";
  button14: "div";
  button15: "div";
  container39: "div";
  avatar3: "div";
  rectangle: "div";
  button16: "div";
  container41: "div";
  button18: "div";
  text: "div";
  button19: "div";
  button20: "div";
  button21: "div";
  button22: "div";
  text2: "div";
  button23: "div";
  button24: "div";
  button25: "div";
  text3: "div";
  button26: "div";
  container42: "div";
  sidebarMenu1: "div";
  frame: "div";
  frame2: "div";
  sidebarMenu3: "div";
  frame3: "div";
  frame4: "div";
  frame5: "div";
  customerInsights: "div";
  frame6: "div";
  frame7: "div";
  image: "div";
  container138: "div";
  selectTemplate: "div";
  container139: "div";
  container140: "div";
  container141: "div";
  lineChart6: "div";
  frame8: "div";
  rectangle66: "div";
  rectangle67: "div";
  rectangle68: "div";
  rectangle69: "div";
  userAnalysis: "div";
  button55: "div";
  viewDemo: "div";
  container142: "div";
  container143: "div";
  container144: "div";
  columnBarChart5: "div";
  chart: "div";
  rectangle2: "div";
  rectangle3: "div";
  rectangle4: "div";
  rectangle5: "div";
  rectangle6: "div";
  rectangle7: "div";
  rectangle8: "div";
  rectangle9: "div";
  rectangle10: "div";
  rectangle11: "div";
  rectangle70: "div";
  rectangle71: "div";
  rectangle72: "div";
  rectangle73: "div";
  marketingsKpi: "div";
  button57: "div";
  viewDemo2: "div";
  container145: "div";
  container146: "div";
  container147: "div";
  insightfulInteractions: "div";
  rectangle74: "div";
  rectangle75: "div";
  rectangle76: "div";
  rectangle77: "div";
  pieChart5: "div";
  pieChart6: "div";
  insightfulInteractions2: "div";
  button59: "div";
  viewDemo3: "div";
  button60: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFinancialperformance__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFinancialperformance__VariantsArgs;
    args?: PlasmicFinancialperformance__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFinancialperformance__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFinancialperformance__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFinancialperformance__ArgProps,
          internalVariantPropNames: PlasmicFinancialperformance__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFinancialperformance__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFinancialperformance";
  } else {
    func.displayName = `PlasmicFinancialperformance.${nodeName}`;
  }
  return func;
}

export const PlasmicFinancialperformance = Object.assign(
  // Top-level PlasmicFinancialperformance renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wireframe5: makeNodeComponent("wireframe5"),
    dataTable: makeNodeComponent("dataTable"),
    button14: makeNodeComponent("button14"),
    button15: makeNodeComponent("button15"),
    container39: makeNodeComponent("container39"),
    avatar3: makeNodeComponent("avatar3"),
    rectangle: makeNodeComponent("rectangle"),
    button16: makeNodeComponent("button16"),
    container41: makeNodeComponent("container41"),
    button18: makeNodeComponent("button18"),
    text: makeNodeComponent("text"),
    button19: makeNodeComponent("button19"),
    button20: makeNodeComponent("button20"),
    button21: makeNodeComponent("button21"),
    button22: makeNodeComponent("button22"),
    text2: makeNodeComponent("text2"),
    button23: makeNodeComponent("button23"),
    button24: makeNodeComponent("button24"),
    button25: makeNodeComponent("button25"),
    text3: makeNodeComponent("text3"),
    button26: makeNodeComponent("button26"),
    container42: makeNodeComponent("container42"),
    sidebarMenu1: makeNodeComponent("sidebarMenu1"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    sidebarMenu3: makeNodeComponent("sidebarMenu3"),
    frame3: makeNodeComponent("frame3"),
    frame4: makeNodeComponent("frame4"),
    frame5: makeNodeComponent("frame5"),
    customerInsights: makeNodeComponent("customerInsights"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    image: makeNodeComponent("image"),
    container138: makeNodeComponent("container138"),
    selectTemplate: makeNodeComponent("selectTemplate"),
    container139: makeNodeComponent("container139"),
    container140: makeNodeComponent("container140"),
    container141: makeNodeComponent("container141"),
    lineChart6: makeNodeComponent("lineChart6"),
    frame8: makeNodeComponent("frame8"),
    rectangle66: makeNodeComponent("rectangle66"),
    rectangle67: makeNodeComponent("rectangle67"),
    rectangle68: makeNodeComponent("rectangle68"),
    rectangle69: makeNodeComponent("rectangle69"),
    userAnalysis: makeNodeComponent("userAnalysis"),
    button55: makeNodeComponent("button55"),
    viewDemo: makeNodeComponent("viewDemo"),
    container142: makeNodeComponent("container142"),
    container143: makeNodeComponent("container143"),
    container144: makeNodeComponent("container144"),
    columnBarChart5: makeNodeComponent("columnBarChart5"),
    chart: makeNodeComponent("chart"),
    rectangle2: makeNodeComponent("rectangle2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle4: makeNodeComponent("rectangle4"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle7: makeNodeComponent("rectangle7"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle70: makeNodeComponent("rectangle70"),
    rectangle71: makeNodeComponent("rectangle71"),
    rectangle72: makeNodeComponent("rectangle72"),
    rectangle73: makeNodeComponent("rectangle73"),
    marketingsKpi: makeNodeComponent("marketingsKpi"),
    button57: makeNodeComponent("button57"),
    viewDemo2: makeNodeComponent("viewDemo2"),
    container145: makeNodeComponent("container145"),
    container146: makeNodeComponent("container146"),
    container147: makeNodeComponent("container147"),
    insightfulInteractions: makeNodeComponent("insightfulInteractions"),
    rectangle74: makeNodeComponent("rectangle74"),
    rectangle75: makeNodeComponent("rectangle75"),
    rectangle76: makeNodeComponent("rectangle76"),
    rectangle77: makeNodeComponent("rectangle77"),
    pieChart5: makeNodeComponent("pieChart5"),
    pieChart6: makeNodeComponent("pieChart6"),
    insightfulInteractions2: makeNodeComponent("insightfulInteractions2"),
    button59: makeNodeComponent("button59"),
    viewDemo3: makeNodeComponent("viewDemo3"),
    button60: makeNodeComponent("button60"),

    // Metadata about props expected for PlasmicFinancialperformance
    internalVariantProps: PlasmicFinancialperformance__VariantProps,
    internalArgProps: PlasmicFinancialperformance__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFinancialperformance;
/* prettier-ignore-end */
